# TODO: Translation updated at 2026-09-25 07:34

translate chinese_simplified strings:
    old "Fallen Noble"
    new "落魄贵族"
    old "Once a respected aristocrat, now disgraced and broke. Your name still opens doors, even as your purse runs empty."
    new "曾是受人尊敬的贵族，如今身败名裂、一贫如洗。你的名字仍能敲开大门，即使钱袋已空。"
    old "Aristocrat"
    new "贵族"
    old "A duelist-courtier who wins with charm and name. Strong charisma, balanced body."
    new "以魅力与名号取胜的决斗家廷臣。魅力出众，身手均衡。"
    old "Charisma +1."
    new "魅力 +1。"
    old "Noble Bearing"
    new "贵族气质"
    old "Reputation gains +25%."
    new "声望获取 +25%。"
    old "May protect a girl when a fight breaks out."
    new "发生斗殴时可以保护一名女孩。"
    old "Sign of Influence"
    new "影响力标志"
    old "Love and fear gains +10% brothel-wide."
    new "全青楼爱与恐惧获取 +10%。"
    old "Inspiring Presence"
    new "鼓舞气场"
    old "All girls' charm +5."
    new "所有女孩魅力 +5。"
    old "Champion's Duel"
    new "勇士决斗"
    old "Fight challenges +6 (dice)."
    new "战斗挑战 +6（骰子）。"
    old "Legacy of the House"
    new "家族传承"
    old "Reputation gains +50%."
    new "声望获取 +50%。"
    old "Street Thug"
    new "街头混混"
    old "Raised in the slums of Zan. Ruthless and resourceful — people mind their manners around you, even if they don't trust you."
    new "在赞恩贫民窟长大。 ruthless 且足智多谋——即使不信任你，人们在你面前也会谨言慎行。"
    old "Enforcer"
    new "打手"
    old "A slum brawler who rules the back alleys. Strong body, iron discipline."
    new "统治后巷的贫民窟打手。身强体壮，纪律如铁。"
    old "Street Brawler"
    new "街头斗殴"
    old "Strength +1."
    new "力量 +1。"
    old "Menacing Glare"
    new "凶恶凝视"
    old "Fear gains +15% brothel-wide."
    new "全青楼恐惧获取 +15%。"
    old "Iron Discipline"
    new "铁血纪律"
    old "Obedience targets -10 for training and jobs brothel-wide."
    new "全青楼训练与工作服从目标 -10。"
    old "Thick Skin"
    new "皮糙肉厚"
    old "Spirit +1."
    new "精神 +1。"
    old "Bloodhound"
    new "寻血猎犬"
    old "Kingpin"
    new "黑帮老大"
    old "Underworld Connections"
    new "地下关系"
    old "Kidnap success +20%. Starting evil reputation +10."
    new "掳人成功率 +20%。起始邪恶声望 +10。"
    old "Merchant Family"
    new "商人世家"
    old "Born into a trading house. You know how to haggle, spot a good deal, and make gold talk."
    new "出身贸易世家。你懂得讨价还价、发现好买卖，让金币替你说话。"
    old "Magnate"
    new "豪商"
    old "A guild magnate who turns every coin twice. Sharp charisma, deep pockets."
    new "让每枚金币翻两倍的行会豪商。魅力锋利，口袋深厚。"
    old "Buy prices -2%, sell prices +2% (scales with charisma)."
    new "买价 -2%，卖价 +2%（随魅力缩放）。"
    old "Sharp Deal"
    new "精明交易"
    old "Shop prices -15%."
    new "商店价格 -15%。"
    old "Golden Touch"
    new "点金之手"
    old "Sell prices +3% (scales with charisma)."
    new "卖价 +3%（随魅力缩放）。"
    old "Trade Empire"
    new "商业帝国"
    old "Shop prices -15%. Starting gold +500."
    new "商店价格 -15%。起始金币 +500。"
    old "Wandering Mage"
    new "流浪法师"
    old "A self-taught spellcaster seeking fortune. Girls are drawn to your mysterious aura."
    new "自学成才、寻求财富的施法者。女孩们被你神秘的气场吸引。"
    old "Sorcerer"
    new "咒术师"
    old "A wandering caster weaving auras over the brothel. Deep spirit, fragile body."
    new "在青楼上编织光环的流浪施法者。精神深厚，身体脆弱。"
    old "All girls' beauty +5."
    new "所有女孩容貌 +5。"
    old "All girls' body +5."
    new "所有女孩身材 +5。"
    old "Meditation"
    new "冥想"
    old "All girls' refinement +5."
    new "所有女孩气质 +5。"
    old "Arcane Focus"
    new "奥术专注"
    old "Spell learning +30%."
    new "法术学习 +30%。"
    old "Archmage"
    new "大法师"
    old "Arcane Charm"
    new "神秘魅力"
    old "Pirate Captain"
    new "海盗船长"
    old "A feared sea reaver who lost her ship to mutiny. Zan is where you rebuild your legend — by any means necessary."
    new "令人闻风丧胆的海上掠夺者，船只因哗变失去。赞恩是你重建传奇之地——不择手段。"
    old "Reaver"
    new "掠夺者"
    old "A mutinied sea wolf taking what they want. Hard body, quick hands, no mercy."
    new "被哗变的海上孤狼，予取予求。身体硬朗，手脚麻利，毫不留情。"
    old "Boarding Party"
    new "跳帮强袭"
    old "Kidnap success +20%."
    new "掳人成功率 +20%。"
    old "Plunder"
    new "劫掠"
    old "Sea Legs"
    new "水手平衡"
    old "Dread Captain"
    new "恐怖船长"
    old "Raiding Party"
    new "劫掠小队"
    old "Sell prices +5% (plunder sells well). Starting gold +200."
    new "卖价 +5%（赃物好出手）。起始金币 +200。"

