# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old "%i%% chance of ignoring hurt damage"
    new "有 %i%% 的几率忽略伤害"
    old "Cannot be hurt"
    new "不会受伤"
    old "set %s%s"
    new "设置 %s%s"
translate chinese_simplified strings:

    # game/core/framework/character.rpy:543
    old "Did not provide value for %s"
    new "未提供 %s 的值"

# TODO: Translation updated at 2026-09-11 20:16

translate chinese_simplified strings:
    old "Accepts nudity"
    new "接受裸露"
    old "+1 level (max level: %s)"
    new "+1 级（最高等级：%s）"
    old "Increases the power of your advertising girls (higher bonuses to brothel reputation, customer attraction and customer budget)."
    new "增强你的宣传姑娘（对青楼声望、吸引客人和客人预算的加成更高）。"
    old "Heals a wounded minion."
    new "治疗一名受伤的仆从。"
    old "she may work a half-shift, then whore a half-shift."
    new "她可以上半班工作，再上半班接客。"
    old "higher chance of critical success when working or whoring (does not stack)"
    new "工作或接客时大成功的几率更高（不叠加）"
    old "higher chance of critical failure when working or whoring"
    new "工作或接客时大失败的几率更高"
    old "may talk an unwilling customer into accepting a different sex act"
    new "可以说服不情愿的客人接受另一种性服务行为"
    old "chance of stealing an extra 10% tip from a customer, lowers reputation if caught"
    new "有几率从客人处偷取额外10%的小费，被抓住会降低声望"
    old "Customers have a small chance to 'forget' a random item in her care."
    new "客人有小几率把一件随机物品“遗忘”在她那里。"
    old "may get a customer satisfaction boost if her beauty, body, charm or refinement skill is high enough"
    new "若她的美貌、身材、魅力或优雅足够高，可能获得客人满意度加成"
    old "may get a customer satisfaction boost if her libido, obedience, constitution or sensitivity skill is high enough"
    new "若她的性欲、服从、体质或敏感足够高，可能获得客人满意度加成"
    old "mood increase when whoring"
    new "接客时心情提升"
    old "may earn prestige when working"
    new "工作时可能获得威望"
    old "every night, she will help other girls with lower skills receive a permanent skill increase (one girl per rank)"
    new "每晚她会帮助技能较低的姑娘获得永久技能提升（每个等级一名姑娘）"
    old "doubles the base chance of perks activating (up to a maximum of 50%)"
    new "天赋激活的基础几率翻倍（最高50%）"
    old "you can defend the brothel once, even when you are out of AP"
    new "即使行动力耗尽，你也可以保卫青楼一次"
    old "you can defend the brothel an unlimited amount of times even when you are out of AP"
    new "即使行动力耗尽，你也可以无限次保卫青楼"
    old "hypnosis never fails"
    new "催眠永不失败"
    old "excludes up to %s gold from the brothel threat level"
    new "从青楼威胁等级中排除至多%s金币"
    old "+25% to tip and reputation gains if she has only one activated sex act (not including bisexual and group)"
    new "若她只激活一种性服务行为（不含双人和群交），小费和声望获取+25%"
    old "when resting, may cast a magic shield on herself or a friend to protect from attacks"
    new "休息时，可能为自己或同伴施放魔法护盾抵御攻击"
    old "ignores customer budget limitations"
    new "无视客人预算限制"
    old "Chance of ignoring energy loss during each interaction"
    new "每次互动时有几率无视体力流失"
    old "Successful hypnosis attempts have a chance to affect more girls in the brothel"
    new "成功的催眠有机会影响青楼中更多的姑娘"
    old "She is available for bisexual acts."
    new "她可以提供双人性服务。"
    old "She is available for group sex acts."
    new "她可以提供群交服务。"
    old "She is available for bisexual group sex acts."
    new "她可以提供双人群交服务。"
    old "Adds 2 points of advertising per Rank."
    new "每级增加2点宣传。"
    old "accelerates a girl's healing by %s day(s)."
    new "使一名姑娘的康复加速%s天。"
    old "Allows you to increase customers' %s by up to +%s%%."
    new "使你可以将客人的%s提高至多+%s%%。"
    old "Allows %s to visit your brothel."
    new "允许%s光顾你的青楼。"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "had"
    new "曾经"
    old "rerolling "
    new "重新掷骰 "
    old " when working"
    new " 工作时"
    old " (for "
    new "（持续 "
    old " turns - does not stack)"
    new " 回合 - 不叠加）"
    old "1 turn - does not stack)"
    new "1 回合 - 不叠加）"

