# TODO: Translation updated at 2026-06-12 05:58

translate chinese_simplified strings:
    old "Would you like to reset this mod for this game (recommended)?"
    new "您想重置此游戏的模组吗（推荐）？"
    old "A new mod has been activated: "
    new "一个新的模组已启用："
    old "Are you sure you want to repay your loan in full for "
    new "你确定要全额偿还贷款吗？"
    old """
%s has been activated."""
    new " %s 已被激活。"
    old """
%s has been deactivated."""
    new " %s 已被停用。"
    old "-%s AP"
    new "-%s AP"
    old "+%s %s"
    new "+%s %s"
    old "I'm sorry, you just don't have enough %s to pay for this."
    new "抱歉，你没有足够的%s来支付这笔费用。"
    old "{color=[c_crimson]}%s has forgotten %s{/color}"
    new "{color=[c_crimson]}%s 忘记了 %s{/color}"
    old "%s: This spell is already active."
    new "%s：此法术已生效。"
    old "Another %s spell is already active."
    new "另一个%s法术已经生效。"
    old "%s has been activated."
    new "%s 已被激活。"
    old "%s: You do not have enough mana to cast this spell."
    new "%s：你的法力值不足以施放此法术。"
    old "Only one %s spell can be automated."
    new "只能自动化一个%s法术。"
    old "Unknown MC skill: %s"
    new "未知主角技能：%s"
    old "%s's %s: +%i"
    new "%s 的 %s：+%i"
    old "%s: You cannot sell this item."
    new "%s：您不能出售此物品。"
    old "Warning: This item is not instantiated (%s)."
    new "警告：此项目尚未实例化（%s）。"
    old "%s: You cannot give this item."
    new "%s：您不能赠送此物品。"
    old "%s: You cannot give this item to this person."
    new "%s：您不能将此物品交给此人。"
    old "Warning: This item cannot be removed, it is not instantiated (%s)."
    new "警告：此项目无法移除，它尚未实例化 (%s)。"
    old "Warning: This item cannot be added, it is not instantiated (%s)."
    new "警告：此项目无法添加，它尚未实例化 (%s)。"
    old "%s is wounded for %i days."
    new "%s 受伤 %i 天。"
    old "Missing resources"
    new "缺失的资源"
    old "You are missing the resources needed for this upgrade (%s %s)."
    new "您缺少此升级所需的资源（%s %s）。"
    old "Alarm set for %i (%s)"
    new "为 %i (%s) 设了闹钟"
    old "Mod Update"
    new "模组更新"
    old "%s has been deactivated. Would you like to deactivate this mod for this game?"
    new "%s 已被停用。你要在这个游戏中停用此模组吗？"
    old "A new mod has been activated: %s. Would you like to activate this mod for this game?"
    new "新模组已激活：%s。你要在这个游戏中激活此模组吗？"
    old "Failure to deactivate %s"
    new "停用 %s 失败"
    old "Are you sure you want to repay your loan in full for %s gold?"
    new "你确定要一次性还清 %s 金币的贷款吗？"
    old "filtering"
    new "筛选中"
translate chinese_simplified strings:

    # game/core/framework/core_entities.rpy:104
    old "WARNING. Activating cheats will disable achievements for this game. It will not affect achievements you already have. This decision cannot be reversed.\\n{b}Are you sure you want to activate cheats for this game?{/b}"
    new "警告。激活作弊将禁用本游戏的成就。它不会影响你已获得的成就。此决定无法撤销。\n{b}你确定要为本游戏激活作弊吗？{/b}"

    # game/core/framework/core_entities.rpy:211
    old "%s couldn't be found. Would you like to deactivate this mod for this game (recommended)?"
    new "找不到 %s。你想在本游戏中停用此模组吗（推荐）？"

    # game/core/framework/core_entities.rpy:215
    old "A different version of mod: %s has been found (%s)."
    new "发现了不同版本的模组：%s（%s）。"

