# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old "You have sold the %s to %s."
    new "您已将 %s 出售给 %s。"
    old "%s is not a valid job or sex act for %s."
    new "%s 不是 %s 的有效工作或性行为。"
    old "Difficulty is related to customer population and averaged among all targeted customers."
    new "难度与客户群体相关，并以所有目标客户的平均值为准。"
    old "Base modifier: %s"
    new "基础修正值：%s"
    old " (%i wanted to do something else)"
    new "（%i人原本想做别的事情）"
    old """
Perks and special effects: %s"""
    new "特长和特殊效果：%s"
    old "Group sex modifier: %s"
    new "群体性别修饰符：%s"
    old "Bisexual sex modifier: %s"
    new "双性恋性别修饰符：%s"
    old "Chosen sex act modifier: %s"
    new "选择的性行为修饰符：%s"
    old """
Job Mod modifier: %s"""
    new "职业修改器：%s"
    old """
Room modifier: %s"""
    new "房间修改器：%s"
    old "First customer bonus: %s"
    new "首单奖励：%s"
    old "Deep throat: %s"
    new "深喉：%s"
    old "Bukkake: %s"
    new "喷射：%s"
    old "Creampie: %s"
    new "奶油派：%s"
    old "Anal creampie: %s"
    new "肛交奶油派：%s"
    old "Cum on face: %s"
    new "射在脸上：%s"
    old "Customer satisfaction: %s"
    new "客人满意度：%s"
    old "Skill modifier (%s): %s ({i}%s{/i})"
    new "技能修正值（%s）：%s（{i}%s{/i}）"
    old """
Sensitivity modifier: %s"""
    new "灵敏度调节器：%s"
    old """
Job level modifier (%s): %s"""
    new "职业等级修正值（%s）：%s"
    old "Girl skills: %s"
    new "女孩技能：%s"
    old "Skill bonuses"
    new "技能加成"
    old "Represents her performance on a given interaction. She rolled a %i"
    new "表示她在此次互动中的表现。她掷出了%i点。"
    old "She rerolled a %i"
    new "她重新掷骰子掷出了一个%i"
    old "Used %s"
    new "已用%s"
    old """%s: %s
"""
    new " %s: %s"
    old "Perks & special effects: %s"
    new "特权和特效：%s"
    old "Misc. effects: %s"
    new "其他影响：%s"
    old "Miscellaneous"
    new "各种各样的"
    old """
Customer initial budget: %s (%s customers)"""
    new "客户初始预算：%s（%s 位客户）"
    old """
Customer budget limit: %s"""
    new "客户预算限额：%s"
    old """

Pickpocket: %s (%s)"""
    new "扒手：%s (%s)"
    old "Tip: {image=img_gold_20} %s"
    new "提示：{image=img_gold_20} %s"
    old "%s: {image=img_gold} %s"
    new "%s: {image=img_gold} %s"
    old "Total tip (%s)"
    new "小费总额（%s）"
    old "Total tip"
    new "总小费"
    old "Customer budget: Unlimited"
    new "客户预算：无限制"
    old " (maxed)"
    new " （已达上限）"
    old "Customer budget: %i"
    new "客户预算：%i"
    old "%s changes"
    new "%s 变化"
    old """%s is a level %i %s.

%s"""
    new "%s 是级别 %i %s。 %s"
    old "LEVEL UP"
    new "升级"
    old " is ready to level up (%i -> %i)"
    new "准备升级（%i -> %i）"
    old "{color=[c_lightgreen]}XP{/color}: %i/%i (%s)"
    new "{color=[c_lightgreen]}XP{/color}: %i/%i (%s)"
    old "Experience"
    new "经验"
    old """%s: %i
"""
    new " %s: %i"
    old """
Base customers: %s"""
    new "基础客户群：%s"
    old """
Advertising: %s"""
    new "广告：%s"
    old """
Special effects: %s"""
    new "特效：%s"
    old """
Begin step %s: %s customers"""
    new "开始步骤 %s：%s 位客户"
    old """
Skipping %s because it's full"""
    new "跳过 %s，因为它已满"
    old """
Skipping %s because no tickets left"""
    new "跳过 %s，因为没有剩余票数"
    old """
Customer #%s has been assigned"""
    new "客户 #%s 已分配"
    old """
End of step %s, %s customers have been assigned."""
    new "步骤 %s 结束，已分配 %s 位客户。"
    old """

Step: %s (%s whores available)
"""
    new "步骤：%s（%s 名妓女可供选择）"
    old """
%s came """
    new " %s 来了"
    old "and chose %s for %s."
    new "并选择了 %s 作为 %s。"
    old " She brought a friend (%s)."
    new "她带了一位朋友（%s）。"
    old " (%s has spent %s interactions and has %s left)"
    new " （%s 已花费 %s 次互动，还剩 %s 次）"
    old " (%s has no interactions left and was REMOVED)"
    new " （%s 已无交互记录，已被移除）"
    old "%s: Assault attempt"
    new "%s：袭击未遂"
    old """
{color=[c_green]}Fortunately, your security is close at hand. They quickly gang up on him and proceed to beat the crap out of his sorry ass.
{/color}Your girl is safe, and you pocket the content of his wallet: %s gold."""
    new "{color=[c_green]}幸运的是，你的护卫就在附近。他们迅速一拥而上，把那家伙狠狠揍了一顿。{/color}你的女孩安然无恙，而你顺手拿走了他钱包里的财物：%s金币。"
    old "{color=[c_green]}%s Your guards beat him up (%s gold earned).{/color}"
    new "{color=[c_green]}%s 你的护卫狠狠教训了他一顿（获得%s金币）。{/color}"
    old "Averted by security ({image=img_gold} +%i)"
    new "安全措施阻止了（{image=img_gold} +%i）"
    old "Mood +, Fear -"
    new "情绪+，恐惧-"
    old "Averted by you ({image=img_gold} +%i)"
    new "被你避免了（{image=img_gold} +%i）"
    old "Mood +, Love +, Fear --"
    new "情绪+，爱+，恐惧--"
    old "Averted by Magic Shield"
    new "被魔法盾化解"
    old "Mood +"
    new "情绪+"
    old "Averted by Immunity"
    new "免疫力避免了这种情况"
    old "Security failure"
    new "安全故障"
    old "Mood --, Love -, Fear ++"
    new "情绪 --，爱 -，恐惧 ++"
    old " hurt for %i day%s"
    new "疼痛持续了%i天%s"
    old "Averted by herself"
    new "她自己避开了"
    old "%s: Arson attempt"
    new "%s：纵火未遂"
    old """
You work together with your staff and some helpful customers to extinguish the flames. Alas, the place has been badly damaged. Your brothel condition deteriorates by %s."""
    new "你和员工以及一些热心的顾客一起扑灭了火焰。可惜的是，场所损毁严重。你的妓院状况恶化了%s。"
    old "%s: Rape attempt"
    new "%s：强奸未遂"
    old " Even though she refused, the customer tried to force her to do it. "
    new "尽管她拒绝了，但顾客还是试图强迫她这样做。"
    old "Rape attempt"
    new "强奸未遂"
translate chinese_simplified strings:

    # game/core/framework/economy.rpy:18
    old "%s: You cannot trade this item."
    new "%s：你不能交易此物品。"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old " (changed by %s)"
    new "（由 %s 改变）"
    old ", but it turned to a 6 because she is lucky"
    new "，但因为她运气好，结果变成了 6"
    old "Dice roll"
    new "骰子"
    old "\nRewarded bonus: +1"
    new """
奖励加成：+1"""
    old "\nPunished bonus: +1"
    new """
惩罚加成：+1"""
    old "{color=%s}%s result (%i){/color}"
    new "{color=%s}%s 结果（%i）{/color}"
    old "Customers entertained: %i/%i"
    new "接待的顾客：%i/%i"
    old "Customers served: %i/%i"
    new "服务的顾客：%i/%i"
    old "Customer budget is the cumulated amount they are willing to spend on this interaction.\n"
    new "顾客预算是指他们愿意为此次互动花费的累计金额。"
    old "\nShe used %s to improve the mood."
    new """
她用 %s 来改善气氛。"""
    old "JOB SKILL UP"
    new "职业技能提升"
    old "{color=[c_orange]}JP{/color}: %i/%i (%s)"
    new "{color=[c_orange]}JP{/color}：%i/%i（%s）"
    old "Job points"
    new "职业点数"
    old "RANK UP"
    new "等级提升"
    old "{color=[c_softpurple]}Reputation{/color}: %i/%i (%s)"
    new "{color=[c_softpurple]}声望{/color}：%i/%i（%s）"
    old "Energy: {color=%s}%i{/color}/%i (%s)"
    new "体力：{color=%s}%i{/color}/%i（%s）"
    old "Dirt: {color=%s}%s{/color}"
    new "脏乱度：{color=%s}%s{/color}"
    old "Dirt"
    new "脏乱"
    old "Security alert"
    new "安全警报"
    old "Assault attempt"
    new "袭击未遂"
    old "Mood --, Fear ++"
    new "心情 --，恐惧 ++"
    old "Arson attempt"
    new "纵火未遂"
    old "Averted by security"
    new "被安保化解"
    old "{color=[c_green]}You heard %s crying for help and threatened to throw him out. He decided to play nice.{/color}"
    new "{color=[c_green]}你听到 %s 呼救，威胁要把他扔出去，他决定老实点。{/color}"
    old "Averted by you"
    new "被你化解"
    old "Mood +, Love +, Fear -"
    new "心情 +，爱意 +，恐惧 -"
    old "Fortunately, her magic shield protected her. The customer was awed and sheepishly agreed to back off."
    new "幸运的是，她的魔法护盾保护了她。顾客大为敬畏，不好意思地同意作罢。"
    old "{color=[c_red]}You tried to help, but the customer knocked you out and locked the door shut.{/color}"
    new "{color=[c_red]}你试图帮忙，但顾客把你打晕并反锁了房门。{/color}"
    old "{color=[c_green]}%s told him he could play nice or lose an important body part. He changed his mind.{/color}"
    new "{color=[c_green]}%s 告诉他要么老实点，要么丢掉某个重要的身体部位，他改变了主意。{/color}"
    old "{color=[c_red]}%s tried to fight him to no avail, and he had his way with her.{/color}"
    new "{color=[c_red]}%s 试图反抗但无济于事，被他随意摆布。{/color}"

