# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old "%s: You cannot trade this item."
    new "%s：此物品不可交易。"
    old "You have sold the %s to %s."
    new "您已将 %s 出售给 %s。"
    old "%s is not a valid job or sex act for %s."
    new "%s 不是 %s 的有效工作或性行为。"
    old "Difficulty is related to customer population and averaged among all targeted customers."
    new "难度与客户群体相关，并以所有目标客户的平均值为准。"
    old "Base modifier: %s"
    new "基础修正值：%s"
    old " (%i wanted to do something else)"
    new "（%i人原本想做别的事情）"
    old "\nPerks and special effects: %s"
    new "特长和特殊效果：%s"
    old "Group sex modifier: %s"
    new "群体性别修饰符：%s"
    old "Bisexual sex modifier: %s"
    new "双性恋性别修饰符：%s"
    old "Chosen sex act modifier: %s"
    new "选择的性行为修饰符：%s"
    old "\nJob Mod modifier: %s"
    new "职业修改器：%s"
    old "\nRoom modifier: %s"
    new "房间修改器：%s"
    old "First customer bonus: %s"
    new "首单奖励：%s"
    old "Deep throat: %s"
    new "深喉：%s"
    old "Bukkake: %s"
    new "喷射：%s"
    old "Creampie: %s"
    new "奶油派：%s"
    old "Anal creampie: %s"
    new "肛交奶油派：%s"
    old "Cum on face: %s"
    new "射在脸上：%s"
    old "Customer satisfaction: %s"
    new "客人满意度：%s"
    old "Skill modifier (%s): %s ({i}%s{/i})"
    new "技能修正值（%s）：%s（{i}%s{/i}）"
    old "\nSensitivity modifier: %s"
    new "灵敏度调节器：%s"
    old "\nJob level modifier (%s): %s"
    new "职业等级修正值（%s）：%s"
    old "Girl skills: %s"
    new "女孩技能：%s"
    old "Skill bonuses"
    new "技能加成"
    old "Represents her performance on a given interaction. She rolled a %i"
    new "表示她在此次互动中的表现。她掷出了%i点。"
    old "She rerolled a %i"
    new "她重新掷骰子掷出了一个%i"
    old "Used %s"
    new "已用%s"
    old "%s: %s\n"
    new " %s: %s"
    old "Perks & special effects: %s"
    new "特权和特效：%s"
    old "Misc. effects: %s"
    new "其他影响：%s"
    old "Miscellaneous"
    new "各种各样的"
    old "\nCustomer initial budget: %s (%s customers)"
    new "客户初始预算：%s（%s 位客户）"
    old "\nCustomer budget limit: %s"
    new "客户预算限额：%s"
    old "\n\nPickpocket: %s (%s)"
    new "扒手：%s (%s)"
    old "Tip: {image=img_gold_20} %s"
    new "提示：{image=img_gold_20} %s"
    old "%s: {image=img_gold} %s"
    new "%s: {image=img_gold} %s"
    old "Total tip (%s)"
    new "小费总额（%s）"
    old "Total tip"
    new "总小费"
    old "Customer budget: Unlimited"
    new "客户预算：无限制"
    old " (maxed)"
    new " （已达上限）"
    old "Customer budget: %i"
    new "客户预算：%i"
    old "%s changes"
    new "%s 变化"
    old "%s is a level %i %s.\n\n%s"
    new "%s 是级别 %i %s。 %s"
    old "LEVEL UP"
    new "升级"
    old " is ready to level up (%i -> %i)"
    new "准备升级（%i -> %i）"
    old "{color=[c_lightgreen]}XP{/color}: %i/%i (%s)"
    new "{color=[c_lightgreen]}XP{/color}: %i/%i (%s)"
    old "Experience"
    new "经验"
    old "%s: %i\n"
    new " %s: %i"
    old "\nBase customers: %s"
    new "基础客户群：%s"
    old "\nAdvertising: %s"
    new "广告：%s"
    old "\nSpecial effects: %s"
    new "特效：%s"
    old "\nBegin step %s: %s customers"
    new "开始步骤 %s：%s 位客户"
    old "\nSkipping %s because it's full"
    new "跳过 %s，因为它已满"
    old "\nSkipping %s because no tickets left"
    new "跳过 %s，因为没有剩余票数"
    old "\nCustomer #%s has been assigned"
    new "客户 #%s 已分配"
    old "\nEnd of step %s, %s customers have been assigned."
    new "步骤 %s 结束，已分配 %s 位客户。"
    old "\n\nStep: %s (%s whores available)\n"
    new "步骤：%s（%s 名妓女可供选择）"
    old "\n%s came "
    new " %s 来了"
    old "and chose %s for %s."
    new "并选择了 %s 作为 %s。"
    old " She brought a friend (%s)."
    new "她带了一位朋友（%s）。"
    old " (%s has spent %s interactions and has %s left)"
    new " （%s 已花费 %s 次互动，还剩 %s 次）"
    old " (%s has no interactions left and was REMOVED)"
    new " （%s 已无交互记录，已被移除）"
    old "%s: Assault attempt"
    new "%s：袭击未遂"
    old "\n{color=[c_green]}Fortunately, your security is close at hand. They quickly gang up on him and proceed to beat the crap out of his sorry ass.\n{/color}Your girl is safe, and you pocket the content of his wallet: %s gold."
    new "{color=[c_green]}幸运的是，你的护卫就在附近。他们迅速一拥而上，把那家伙狠狠揍了一顿。{/color}你的女孩安然无恙，而你顺手拿走了他钱包里的财物：%s金币。"
    old "{color=[c_green]}%s Your guards beat him up (%s gold earned).{/color}"
    new "{color=[c_green]}%s 你的护卫狠狠教训了他一顿（获得%s金币）。{/color}"
    old "Averted by security ({image=img_gold} +%i)"
    new "安全措施阻止了（{image=img_gold} +%i）"
    old "Mood +, Fear -"
    new "情绪+，恐惧-"
    old "Averted by you ({image=img_gold} +%i)"
    new "被你避免了（{image=img_gold} +%i）"
    old "Mood +, Love +, Fear --"
    new "情绪+，爱+，恐惧--"
    old "Averted by Magic Shield"
    new "被魔法盾化解"
    old "Mood +"
    new "情绪+"
    old "Averted by Immunity"
    new "免疫力避免了这种情况"
    old "Security failure"
    new "安全故障"
    old "Mood --, Love -, Fear ++"
    new "情绪 --，爱 -，恐惧 ++"
    old " hurt for %i day%s"
    new "疼痛持续了%i天%s"
    old "Averted by herself"
    new "她自己避开了"
    old "%s: Arson attempt"
    new "%s：纵火未遂"
    old "\nYou work together with your staff and some helpful customers to extinguish the flames. Alas, the place has been badly damaged. Your brothel condition deteriorates by %s."
    new "你和员工以及一些热心的顾客一起扑灭了火焰。可惜的是，场所损毁严重。你的妓院状况恶化了%s。"
    old "%s: Rape attempt"
    new "%s：强奸未遂"
    old " Even though she refused, the customer tried to force her to do it. "
    new "尽管她拒绝了，但顾客还是试图强迫她这样做。"
    old "Rape attempt"
    new "强奸未遂"

