# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old "%s has a look of sheer terror in her eyes, and she shakes uncontrollably. She moans like a wounded animal if you move even slightly towards her. You can tell that a slight push would be all it takes to send her mind over the edge now."
    new "%s眼中充满了极度的恐惧，身体不受控制地颤抖着。哪怕你只是稍微朝她靠近一点，她都会像受伤的野兽一样发出痛苦的呜咽。你能感觉到，现在只需要再轻轻推她一把，她的精神就会彻底崩溃。"
    old "%s curls and looks around herself in complete panic, her eyes wild with fear. If you insist on using your powers on her, her mind will end up breaking."
    new "%s蜷缩起身体，惊恐地环顾四周，眼神中充满了恐惧。如果你执意继续对她使用你的力量，她的精神最终将彻底瓦解。"
    old "%s looks bewildered, not sure what has been happening to her. Little by little her sanity is beginning to slip."
    new "%s神情恍惚，似乎不明白自己身上究竟发生了什么。她的理智正在一点一点地流失。"
    old "%s seems shaken by what just happened, but puts on a brave face. She looks defiant in spite of what she has been through."
    new "%s显然被刚刚发生的事情吓到了，但她仍努力装出坚强的样子。尽管经历了这一切，她的眼神里依旧带着倔强与反抗。"
    old "%s seems shaken by what just happened, but she tries to keep it to herself. She looks away from you, trying to suppress a sob."
    new "%s显然被刚刚发生的事情吓坏了，但她努力不让别人察觉。她避开你的目光，强忍着即将夺眶而出的泪水。"
    old "As %s returns to normal, she barely seems to register what just happened to her, although you know it must have had a subconscious effect."
    new "当 %s 恢复正常时，她似乎几乎没有意识到刚才发生在她身上的事情，尽管你知道这肯定对她的潜意识产生了影响。"
    old "You have discovered %s's fixation with %s."
    new "你发现了 %s 对 %s 的迷恋。"
    old "You have discovered %s's disgust for %s."
    new "你已经发现了 %s 对 %s 的厌恶。"
    old " : %s"
    new " ：%s"
    old "%s: %s (expired)"
    new "%s: %s（已过期）"
    old "%s: %s (duration: %s days)"
    new "%s: %s（持续时间：%s 天）"
    old "Level: +1"
    new "等级：+1"
    old "This item can only be used up to level %s"
    new "此物品只能在等级达到%s之前使用。"
    old "Only one healing item can be used per day."
    new "每天只能使用一件治疗物品。"
    old "Healing"
    new "康复"
    old "Healed: %s"
    new "已治愈：%s"
    old "(fully healed)"
    new "（已完全康复）"
    old "%s has been healed completely."
    new "%s 已完全康复。"
    old "%s has been healed but still need some time to rest."
    new "%s 已经痊愈，但仍需要一些时间休息。"
    old "%s is in good health."
    new "%s 身体健康。"
    old "Oh, you remembered my favorite color! You're so considerate..."
    new "哦，你居然记得我最喜欢的颜色！你真体贴……"
    old "Ah, em, thanks. You know, I don't like this color, but I appreciate the gesture."
    new "啊，嗯，谢谢。你知道，我不喜欢这个颜色，但我很感激你的好意。"
    old "Flowers! For me! Thank you..."
    new "花！送给我的！谢谢……"
    old "This is very romantic... Was there something you wanted from me?"
    new "这真是太浪漫了……你想要我做什么呢？"
    old "Hmm, no, not really."
    new "嗯，不，其实不是。"
    old "Oh... I see."
    new "我懂了。"
    old "Already at the maximum relationship level. This potion had no effect."
    new "关系已经达到最高等级了。这药水没有任何效果。"
    old "Oh, I love it so much!!! Thank you, thank you!"
    new "哦，我太喜欢了！！！谢谢，谢谢！"
    old "It's nice! Thanks for thinking about me."
    new "太好了！谢谢你想到我。"
    old "Ah, em, thanks. It's an interesting... whatever it is, I guess."
    new "啊，嗯，谢谢。这真是一个有趣的……不管它是什么，我想。"
    old "What the? Ew, take this away from me!"
    new "什么？呃，快把这东西拿走！"
    old "Let's test if say methods break the flow."
    new "我们来测试一下这些方法是否会破坏流程。"
    old "Did my love go up? Now it's %s"
    new "我的爱意上升了吗？现在是%s"
    old "Did my love go down now? It's %s"
    new "我的爱就此消逝吗？是%s"
    old "Base XP vs Difficulty: %s"
    new "基础经验值与难度：%s"
    old """
Perks & special effects: x%s"""
    new "天赋与特殊效果：x%s"
    old """
Job Mod modifier: x%s"""
    new "职业修正值：x%s"
    old """

Difficulty modifier: x%s"""
    new "难度调整值：x%s"
    old "Base JP vs customers: %s"
    new "基础日本用户与客户对比：%s"
    old """
Girl rank vs Customer rank: %s
"""
    new "女孩排名 vs 顾客排名：%s"
    old " result: %s"
    new "结果：%s"
    old "No reputation change: customer rank too low."
    new "信誉度不改变：客户排名太低。"
    old "Reputation increase vs Customers: +%s"
    new "客户声望提升：+%s"
    old """
First customer: x%s"""
    new "首位客户：x%s"
    old "Reputation decrease vs Customers: %s"
    new "客户声望下降：%s"
    old "No change."
    new "没有变化。"
    old """Base tip: {image=img_gold}%i(Lost virginity: {image=img_gold}+100)
"""
    new "基础提示：{image=img_gold}%i(失去童贞：{image=img_gold}+100)"
    old """Base tip: {image=img_gold}%i
"""
    new "底部尖端：{image=img_gold}%i"
    old """
Naked bonus: x%s"""
    new "裸体奖励：x%s"
    old """
Bisexual bonus: %s"""
    new "双性恋加分：%s"
    old """
Group bonus: x%s"""
    new "团队加成：x%s"
    old """
Result bonus: x%s"""
    new "结果加成：x%s"
    old """
Perks and special effects: x%s"""
    new "特效和特殊效果：x%s"
    old """
Customer mood avg: x%s"""
    new "客人平均情绪倍率：x%s"
    old """
Customer mood tip chance avg: x%s"""
    new "客人情绪提示触发率平均值：x%s"
    old """
{i}Total modifier cannot exceed x%s{/i}"""
    new " {i}总修饰符不能超过 x%s{/i}"
    old """
Act modifier: x%i"""
    new "行动修正值：x%i"
    old """

Extra tip: {image=img_gold}%s"""
    new "额外提示：{image=img_gold}%s"
    old " (Five stars perk: {image=img_gold}%s"
    new " （五星级特权：{image=img_gold}%s"
    old """

= {image=img_gold}%i"""
    new " = {image=img_gold}%i"
    old "%s is immune to getting hurt."
    new "%s 不会受伤。"
    old "%s is hurt for %i day%s."
    new "%s 受伤 %i 天%s。"
    old " was so tired that she fell sick for %i day%s"
    new "她太累了，病了 %i 天 %s"
    old "XP: %s"
    new "XP：%s"
    old " JP: %s"
    new " JP：%s"
    old "Reputation: %s"
    new "信誉：%s"
    old "%s cannot work as a whore anymore."
    new "%s 不能再做妓女了。"
    old """ : She has friends (%s).
"""
    new "她有朋友（%s）。"
    old """ : She has rivals (%s).
"""
    new "她有竞争对手（%s）。"
    old """
She is vulnerable to farm %ss."""
    new "她容易受到农场%ss的影响。"
    old "You notice that %s is feeling a mix of pleasure and discomfort during %s. It seems she has ambivalent feelings about it."
    new "你注意到，%s 在 %s 期间感到既愉悦又不适。她似乎对此感到矛盾。"
    old "You notice that %s seems to enjoy %s."
    new "你注意到 %s 似乎很喜欢 %s。"
    old "You notice that %s seems disgusted by %s."
    new "你注意到 %s 似乎对 %s 感到厌恶。"
    old "former free girl"
    new "前自由女孩"
    old "free girl"
    new "自由女孩"
    old "slave"
    new "奴隶"
    old " from "
    new " 来自"
    old "You do not know her story."
    new "你不知道她的故事。"
    old "You know a few things about her story."
    new "你对她的故事略知一二。"
    old "You know some things about her story."
    new "你对她的故事有一些了解。"
    old "She has told you her story, but you haven't done anything about it yet."
    new "她已经告诉了你她的故事，但你还没有为此做任何事。"
    old "You know about her story."
    new "你了解她的故事。"
    old "You know about her story, and did something about it."
    new "你了解她的故事，并且为此做了一些事。"
    old "You don't know anything about her tastes."
    new "你对她的喜好一无所知。"
translate chinese_simplified strings:
    old """{color=[c_bad]}No profile or portrait picture could be found for the following girl: %s.{/color}
Please rename at least one of her pictures to include the words 'profile' or 'portrait'
(e.g.: 'profile3.webp')
Alternatively, completely delete her directory, restart the game and then go to the Help Menu and 'Repair Girl/MC Pictures' to remove her."""
    new "{color=[c_bad]}找不到以下女孩的个人资料或肖像照片：%s。{/color}\n请至少重命名她的一张照片，以包含“个人资料”或“肖像”字样\n（例如：“profile3.webp”）\n或者，完全删除她的目录，重新启动游戏，然后转到“帮助”菜单和“修复女孩/MC 图片”将其删除。"
    old "%s JP: %s"
    new "%s JP: %s"
    old "%s cannot remain a whore if you deactivate all sex acts. She has been set to rest."
    new "如果你停用了所有性行为，%s 就不能继续做妓女。她已被设置为休息。"
    old "Label: {color=[c_red]}%s{/color} doesn't exist (Custom girl: {color=[c_red]}%s/_BK.ini{/color})."
    new "标签：{color=[c_red]}%s{/color} 不存在（自定义女孩：{color=[c_red]}%s/_BK.ini{/color}）。"

# TODO: Translation updated at 2026-06-25 01:53

translate chinese_simplified strings:

    # game/core/framework/girlclass.rpy:322
    old "A long, inhumane shriek sends shivers down your spine. It came from %s, who is white with terror and on the verge of collapsing. This can't be good..."
    new "一声漫长、非人的尖叫让你脊背发凉。它来自 %s，她吓得脸色苍白，快要崩溃了。这绝不是好事……"

    # game/core/framework/girlclass.rpy:5138
    old " is a "
    new " 是一个 "

