# TODO: Translation updated at 2026-06-12 05:03

translate chinese_simplified strings:
    old "Tell her to remain naked at all times"
    new "告诉她要一直保持裸体状态"
    old "She's crying uncontrollably, she seems very upset. What do you do?"
    new "她哭个不停，看起来非常难过。你该怎么办？"
    old "You're doing well"
    new "你做得很好。"
    old "Stop bitching"
    new "别抱怨了"
    old "I appreciate your efforts"
    new "我感谢你的努力。"
    old "Know your place!"
    new "认清自己的位置！"
    old "You're a big help"
    new "你帮了我很大的忙。"
    old "Just shut up"
    new "闭嘴。"
    old "Keep making friends"
    new "继续结交朋友"
    old "[inter.other_girl.name] is great"
    new "[inter.other_girl.name] 很棒"
    old "[inter.other_girl.name] is stupid"
    new "[inter.other_girl.name] 很蠢"
    old "Stop being friendly with [inter.other_girl.name]"
    new "停止与[inter.other_girl.name]友好相处"
    old "Stop fighting with [inter.other_girl.name]"
    new "停止和[inter.other_girl.name]打架"
    old "Good to hear"
    new "很高兴听到这个消息"
    old "Sorry to hear that"
    new "听到这个消息真遗憾。"
    old "Keep working hard, or else..."
    new "继续努力，否则……"
    old "Get used to it"
    new "习惯就好"
    old "Thank you, I appreciate that"
    new "谢谢，我很感激。"
    old "Train her gently"
    new "温柔地训练她"
    old "Train her normally"
    new "正常训练她"
    old "Train her anyway"
    new "无论如何都要训练她。"
    old "Rough her up"
    new "粗暴对待她"
    old "Admonish her"
    new "训斥她"
    old "Hypnosis is more efficient when exploiting your girl's existing emotions. Which technique will you use to train [girl.name]?"
    new "利用女孩现有的情感进行催眠效果更佳。你会使用哪种技巧来训练[girl.name]？"
    old "How much gold do you want to give her?"
    new "你想给她多少黄金？"
    old "[low] gold"
    new "[low]金币"
    old "[med] gold"
    new "[med]金币"
    old "[high] gold"
    new "[high]金币"
    old "How long do you want her to remain in the farm?"
    new "你想让她在农场待多久？"
    old "You know that [girl.name] has [reaction] for [act] acts. Do you want to try to use it against her?"
    new "你知道[girl.name]对[act]的行为有[reaction]反应。你想利用这一点来对付她吗？"
    old "How do you react?"
    new "你会作何反应？"
    old "You think about what she said. Perhaps there is something you could do to help her?"
    new "你仔细想了想她说过的话。或许你可以做点什么来帮助她？"
    old "Tell her you will perform an exorcism ritual (2 days)"
    new "告诉她你将进行驱魔仪式（2天）。"
    old "Tell her that she has to learn to live with it (replace her negative trait with the 'clumsy' trait)"
    new "告诉她她必须学会接受这一点（用“笨拙”这个特质替换她的缺点）。"
    old "Summon a slimy tentacle to her room for the night (1 day)"
    new "召唤一条黏糊糊的触手到她房间待一晚（1天）。"
    old "Pay the magic guild to summon a tentacle monster to her room for the night (1000 gold, 1 day)"
    new "付钱给魔法公会，召唤一只触手怪到她房间待一晚（1000金币，1天）"
    old "Let her gather some ingredients and set up an altar (3 days)"
    new "让她准备一些材料，并设立祭坛（3天）。"
    old "Pay for the ingredients and let her set up an altar (1 day, 650 gold)"
    new "支付材料费用，让她搭建祭坛（1天，650金币）"
    old "Let her speak her mind freely (replace her negative trait with the 'godless' trait)"
    new "让她畅所欲言（将她的负面特质替换为“无神论”特质）。"
    old "Buy her a new pet (800 gold)"
    new "给她买个新宠物（800金币）"
    old "Hire some lawyers to take [girl.name]'s case to court (1250 gold upfront, unknown gains)"
    new "雇佣律师帮[girl.name]打官司（预付1250金币，收益未知）"
    old "Send some thugs to set fire to her old estate (900 gold)"
    new "派几个暴徒去放火烧了她以前的庄园（900金币）"
    old "Conjure up a firestorm inside the estate's wood reserve"
    new "在庄园的林地保护区内引发一场火灾风暴"
    old "Let her go pray for the unfortunate soul (1 day, 500 gold donation)"
    new "让她去为那个不幸的人祈祷吧（1天，捐赠500金币）"
    old "Offer to increase her allowance (replace her negative trait with the 'expensive' trait)"
    new "提议增加她的零花钱（将她的负面特质替换为“昂贵”特质）"
    old "Buy her the dress of her dreams ([dress.price] gold)"
    new "给她买她梦寐以求的裙子（[dress.price] gold）"
    old "Let her go bury her loved ones (2 days, 1000 gold)"
    new "让她去安葬她的亲人（2天，1000金币）"
    old "Organize a public event (1500 gold upfront, unknown gains)"
    new "组织一场公开活动（前期投入 1500 金币，收益未知）"
    old "Kidnap a horse?!? (750 gold)"
    new "绑架一匹马？！（750金币）"
    old "Offer to repay her debt (900 gold)"
    new "提出帮她偿还债务（900金币）"
    old "Give her some time off to visit her family (3 days)"
    new "给她放几天假，让她回家探望家人（3天）。"
    old "Send some goons off to trash the bastard (500 gold)"
    new "派几个喽啰去把那混蛋揍一顿（500金币）"
    old "Hire the thieves guild to rob the bastard blind (750 gold upfront, unknown gains)"
    new "雇佣盗贼公会洗劫那个混蛋（预付750金币，收益未知）"
    old "Send some crooked guards to rob the bastard blind (750 gold upfront, unknown gains)"
    new "派几个奸诈的卫兵去把那混蛋洗劫一空（预付750金币，收益未知）"
    old "Punish her like the bad girl she is"
    new "像惩罚坏女孩一样惩罚她"

# TODO: Translation updated at 2026-06-12 05:58

translate chinese_simplified strings:
    old "Do you really want to leave without training [girl.fullname]?"
    new "你真的想不经过培训就离开吗，[girl.fullname]？"

# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old "What do you want to %s her for?"
    new "你想为了什么而%s她？"
    old "Today, I want you to overcome your disgust for [fix.short_name]."
    new "今天，我希望你们克服对[fix.short_name]的厌恶。"
    old "Today, I want you to overcome your disgust for..."
    new "今天，我希望你们克服对……的厌恶。"
    old "Your rough training has proven too much for her. "
    new "你严苛的训练对她来说太过残酷了。"
    old "She now hates %s for good."
    new "她现在彻底恨透了%s。"

# TODO: Translation updated at 2026-06-19 03:36

# game/core/content/interactions.rpy:5045
translate chinese_simplified slave_story6_5a387cf0:

    # you "Quite a long way from being a sex slave in [_district_name]..."
    you "离成为 [_district_name] 的性奴还有很长的路要走……"

