#!/usr/bin/env python3
"""Restore lost translations from Phase 2 strings.rpy into current strings.rpy."""

import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent.parent
STRINGS_PATH = ROOT / 'game/tl/chinese_simplified/strings.rpy'

def unquote(s):
    return s.replace('\\n', '\n').replace('\\"', '"').replace('\\\\', '\\')

def quote_for_rpy(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')

def parse_text(text):
    pattern = re.compile(
        r'^(\s*#(?:\s*TODO)?\s*[^\n]*)\n'
        r'\s*old\s+"(.*?)"\s*\n'
        r'\s*new\s+"(.*?)"\s*$',
        re.MULTILINE | re.DOTALL
    )
    result = {}
    for m in pattern.finditer(text):
        comment = m.group(1)
        old_u = unquote(m.group(2))
        new_u = unquote(m.group(3))
        has_todo = 'TODO' in comment
        result[old_u] = (new_u, has_todo, comment)
    return result

def get_git_file(commit, path):
    result = subprocess.run(['git', 'show', f'{commit}:{path}'], capture_output=True, text=True, encoding='utf-8', errors='replace')
    return result.stdout

def main():
    print("Reading Phase 2 strings.rpy from git...")
    phase2_text = get_git_file('91c890e', str(ROOT / 'game/tl/chinese_simplified/strings.rpy'))
    phase2 = parse_text(phase2_text)
    
    print(f"Phase 2 entries: {len(phase2)}")
    phase2_translated = sum(1 for k, v in phase2.items() if v[0] and v[0] != k)
    print(f"  Translated: {phase2_translated}")
    
    print("Reading current strings.rpy...")
    with open(STRINGS_PATH, 'r', encoding='utf-8') as f:
        current_text = f.read()
    current = parse_text(current_text)
    
    print(f"Current entries: {len(current)}")
    current_translated = sum(1 for k, v in current.items() if v[0] and v[0] != k)
    print(f"  Translated: {current_translated}")
    
    # Restore lost translations
    restored = 0
    for old_text, (new_text, has_todo, comment) in phase2.items():
        if new_text and new_text != old_text:
            if old_text in current:
                curr_new, curr_todo, curr_comment = current[old_text]
                if curr_new == old_text:  # Current is fallback - restore translation
                    current[old_text] = (new_text, False, curr_comment + " (restored from Phase 2)")
                    restored += 1
    
    print(f"\nRestored {restored} lost translations")
    
    # Rebuild strings.rpy
    output_lines = [
        "# Translation file for chinese_simplified",
        "# Auto-generated by restore_lost.py",
        "",
        "translate chinese_simplified strings:",
        "",
    ]
    
    for old_text, (new_text, has_todo, comment) in sorted(current.items()):
        old_quoted = quote_for_rpy(old_text)
        new_quoted = quote_for_rpy(new_text)
        
        if not comment.strip():
            comment = "    # "
        
        output_lines.append(comment)
        output_lines.append(f'    old "{old_quoted}"')
        output_lines.append(f'    new "{new_quoted}"')
        output_lines.append("")
    
    backup_path = ROOT / "game/tl/chinese_simplified/strings.rpy.backup.restored"
    shutil.copy2(STRINGS_PATH, backup_path)
    
    with open(STRINGS_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(output_lines) + '\n')
    
    final_translated = sum(1 for k, v in current.items() if v[0] and v[0] != k)
    print(f"\nWritten strings.rpy with {len(current)} entries")
    print(f"  Final translated count: {final_translated}")
    print(f"  Backup saved to: {backup_path}")

if __name__ == '__main__':
    main()
