####        BOA HANCOCK GIRL PACK       ####
###     _BK.ini template for BK v0.3     ###

## This optional file contains advanced config data about a particular girl.
## Variables you don't need can be left out/deleted.
## The file should be named '_BK.ini' and dropped inside the relevant girl folder.
## Full line comments are introduced with a double hash (##)
## Same line comments are added using a hash (#) or a semi-colon sign (;)
## Note: Cloning Options are now part of each section, but legacy format with a dedicated [cloning options] section is still supported.


[identity]

## Girl Name ##

first_name = "Hancock"      # If absent or empty, first name will be randomized
last_name = "Boa" 	        # If absent or empty, no last name will be used
inverted_name = True 	    # If True, the full name will display the last name before the first name, e.g.: 'Boa Hancock'

## Girl Pack Data ##

creator = "Goldo"           # Your name as you would like it to be remembered for the ages
version = "v2023_03_27"     # Version is displayed in the girl mix screen and should help players find out how up to date your girl pack is. You can use any format you prefer.
description = "A sample _BK.ini file to illustrate the basic customization features." # Description will be displayed in the girl mix screen.

## Cloning Options ##
## These options define how 'clones' of the original girl behave at generation.
## There can be only one original girl at once in the game, and any number of clones.
unique = False              # If True, clones will not spawn, only the original girl. All the other cloning options will have no effect.
keep_first_name = False     # If True, clones will keep the same first name
keep_last_name = True       # If True, clones will keep the same last name
keep_inverted = True        # If True, clones will keep the same options for inverted names


[base skills]

## Girl Skills ##
## Rank starting skills from 1 to 5 (1 is terrible, 3 is average, 5 is superb. The game will add some variation.)
## Leave it out or set the value to 0 for a randomized skill level

beauty = 5
body = 0
charm = 0
refinement = 0
libido = 0
obedience = 0
constitution = 0
sensitivity = 0

## Cloning Options ##
keep_skills = True  # If True, clones will keep the same base skill repartition


[base positive traits]

## A girl may only have 2 positive traits in vanilla BK. Gold traits are included in positive traits.
## Trait names must be between quotes (""), spelled exactly as they are in-game. See BKtraits.rpy for the full list of trait names.

## The girl will ALWAYS have these traits (up to maximum nb of traits). Use with caution as it makes girl generation very predictable.
always = []

## The girl will more often have these traits than normal.
often = ["Long legs", "Nice boobs", "Resilient", "Good tits", "Seductive", "Beautiful", "Fit", "Tough", "Sexy", "Brave", "Strong"]

## The girl will less often have these traits than normal.
rarely = ["Sweet", "Meek", "Obedient", "Humble", "Naughty"]

## The girl will NEVER have these traits.
never = []


[base negative traits]

## Reminder, in vanilla BK a girl may only have 1 negative trait.
## Trait names must be between quotes (""), spelled exactly as they are in-game. See BKtraits.rpy for the list of trait names.

## the girl will ALWAYS have these traits (up to maximum nb of traits). Use with caution as it makes girl generation very predictable.
always = []

## The girl will more often have these traits than standard girls.
often = ["Mean", "Cold", "Rough", "Defiant", "Distrustful", "Brutal"]

## The girl will less often have these traits than standard girls.
rarely = ["Plain", "Weak", "Scruffy", "Frail", "Vulnerable"]

## The girl will NEVER have these traits.
never = []

## Cloning Options ##
keep_traits = True  # If True, clones will keep the same base positive and negative trait settings.


[base personality]

## Standard Personality Settings ##
## There are 24 personality types in the game. You can add a custom one.
## A girl can have only one personality. See 'gpersonalities' in BKinit_variables.rpy for the list of personality names.

always = [] # Use with care: it makes girl generation very predictable.
often = ["cold", "superficial"]
rarely = ["sweet", "nerd"]
never = ["meek"]

## Cloning Options ##
keep_personality = True     # If True, clones will keep the same personality (and custom personality) options


[custom personality]

## Custom Personality Settings ##
## You can set a custom personality for the girl here. This will override the 'Base personality' settings
## See 'gpersonalities' in BKinit_variables.rpy for examples of game personalities

custom_personality = False          # set to True to use a custom personality. This will override the 'Base personality' settings.
personality_name = ""               # give a name to that personality (warning: using an existing personality name will override that personality)
description=""                      # this text will display in the magic notebook when a girl's personality is known
attributes = ("", "")               # list a pair of attributes the personality will always have (warning: having more than 2 will cause bugs).
dialogue_personality_weight=3       # how much weight personality-based lines will be given compared to attribute-based and generic dialogue
dialogue_attribute_weight=1         # how much weight attribute-based lines will be given compared to personality-based and generic dialogue
personality_dialogue_only = None    # A list of topics (with quotes, between [] brackets) for which only personality-based dialogue is allowed (e.g. ["slave first visit", "slave train beg"]). All topics can be found in BKdialogue.rpy.

## Custom Dialogue Label ##
## If provided (as a string, between quotes), refers to a custom label that will be called before dialogue is processed
## The label must take the following arguments: girl, topic. This allows the application of advanced game logic.
## See Boa Hancock _events.rpy by Goldo for an example.

custom_dialogue_label="boa_custom_dialogue"


[tastes]

## Tastes are used in chatting dialogue, and for flavor only. You may include answers that are not in vanilla choices.
## Leave the line out or set it to 'None' (without quotes) to randomize

favorite_color = "red"
favorite_food = "hot pot"
favorite_drink = "rhum"

disliked_color = "green"
disliked_food = "devil fruit"
disliked_drink = "beer"

hobbies = ["ruling", "kicking small animals"] # Hobbies must be a list of two items.


[sexual preferences]

## Sex Acts ##
## You can choose positive or negative acts which will be generated more often for this girl (possible choices are: "naked", "service", "sex", "anal", "fetish", "bisexual" and "group").

favorite_acts = ["bisexual"] # (Boa Hancock comes from an all-girl island and resents men)
disliked_acts = []

## Fixations ##
## You can choose positive or negative fixations which will be generated more often for this girl. Fixations names are found in 'fix_dict' in the 'BKinit_variables.rpy' file

always_fixations = []           # Always positive. Use with care: it makes girl generation very predictable.
never_fixations = []            # Never positive.
favorite_fixations = []         # More chance of generating as positive fixation, less as negative.
disliked_fixations = []         # More chance of generating as negative fixation, less as position.
always_negative_fixations = []  # Always negative. Use with care: it makes girl generation very predictable.
never_negative_fixations = []   # Never negative.

## Prior Sexual Experience ##
sexual_experience = "average"   # How much sexual experience she has prior to meeting the player. You can choose between the following: "very experienced", "experienced",  "average", "inexperienced", "very inexperienced", "random". If left out or empty, a random level of experience will be chosen.

## Farm weakness ##
farm_weakness = "beast"         # choose between the following values: "stallion", "beast", "monster", "machine", "random"

## Cloning Options ##
keep_sex = True                 # If True, clones will keep the same sexual preferences, experience and weaknesses.


[background story]

## Girl Generation ##
generate_as = "all"             # Can be set to 'all' or restricted to 'free', 'slave' or 'story'. Story girls never generate on their own, only during custom events.
generate_in = "all"             # Can be set to "all" or a district or location name that must be spelled exactly as in game (including the 'The' article for districts). Handles where the girl will generate as a free girl. No effect on slave girls.
move_after_meeting = True       # Used with the generate_in option (default=True). If True, free girls will move from their starting location normally each week after they have their first interaction with the player. If False, they remain in place.

## Origin ##
## You can provide a custom origin (if you do, make sure to include the origin description below), or just "random".
## Origin description must be written in the girl's own words

origin = "Amazon Lily"
origin_description = "Amazon Lily is the island of the Kuja, an all-female warrior tribe. Pirates often raid us because we make prized sex slaves, but we give them a hell of a time when they try."

## Basic Story ##
## Random slave story: write the story name(s) between quotes, as found in BKinit_variables.rpy (e.g. "slave_story1", "slave_story2"...)

always_slave_story = []
often_slave_story = []
rarely_slave_story = []
never_slave_story = []

## Custom Story ##
## If provided, this label will be called instead of a random back-story. It must take 'girl' as an argument. Replaces the random slave story above.
## See the 'slave_story' labels in BKinteractions.rpy for examples of how it might work (feel free to set up the events very differently)

story_label = None # provide the custom label name (between quotes)

## Custom City Event ##
## If provided, this label will be called instead of normal city interactions. It must take 'girl' as an argument.
## The regular dialog options can be called from within this custom label by using 'call free_girl_talk(girl)'

city_label = "boa_hancock_city" # provide the custom label name (between quotes)

## Custom Night Event ##
## If provided, this label will be called every night. It must take the 'girl' argument. This could be useful to increment some values, run some tests or reset interactions.
## It is recommended that such labels run silent and add a StoryEvent if necessary.

night_label = "boa_hancock_night_check" # provide the custom label name (between quotes)

## Custom Interaction ##
## This adds a custom button to the regular slave interact menu. Leave it out or set value to None or empty brackets if you are not using it.

interact_prompt = ("Visit her room", "boa_hancock_interact", 1) # The first string refers to the caption of the button. The second is the label which will be called upon clicking the button. The integer is the AP cost (for UI display only, it isn't deducted from MC actions outside of your label code for flexibility). It must take 'girl' as an argument.

## Custom Initialization Function ##
## If provided, this function will be called when a girl with this template is created, after randomization.
## Write the function in an init block in _events.rpy or another custom .rpy file.
## It must take 'girl' as an argument. It must not interrupt game flow (python only, no ren'py calls or jumps).

init_function = "my_dumb_function" # provide a custom function name that is called after girl creation (between quotes)

## Cloning Options ##
keep_generate_as = True     # If False, clones will be generated both as slave and free girls regardless of the original setting. True will keep the 'generate_in' setting as well
keep_background = True      # If True, clones will keep the same origin and background story events
keep_interactions = True    # If True, clones will keep the same interactions options and custom city/night events
keep_init = True            # If True, clones will keep the same init function


[cloning options]
## This section is no longer needed, but still supported for legacy girl packs (and will remain supported in the future).

#### END OF FILE ####
