#!/usr/bin/env python3
"""
Merge existing translations with newly extracted strings from __() calls.

Usage:
    python merge_translations.py

Scans game/**/*.rpy for __("...") calls, reads existing translations from
strings.rpy, and writes a merged strings.rpy preserving old translations
and adding new strings with English fallback.
"""

import glob
import os
import re
import sys
from collections import OrderedDict

STRINGS_RPY = "game/tl/chinese_simplified/strings.rpy"
BACKUP_RPY = "game/tl/chinese_simplified/strings.rpy.backup"

def quote_for_rpy(s: str) -> str:
    """Escape a string for use inside Ren'Py double quotes."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')

def unquote_rpy(s: str) -> str:
    """Unescape a Ren'Py quoted string."""
    result = []
    i = 0
    while i < len(s):
        if s[i] == '\\' and i + 1 < len(s):
            nxt = s[i + 1]
            if nxt == 'n':
                result.append('\n')
            elif nxt == 'r':
                result.append('\r')
            elif nxt == 't':
                result.append('\t')
            elif nxt == '"':
                result.append('"')
            elif nxt == '\\':
                result.append('\\')
            else:
                result.append(nxt)
            i += 2
        else:
            result.append(s[i])
            i += 1
    return ''.join(result)

def extract_strings():
    """Scan .rpy files for _() and __() calls. Returns dict: text -> (filepath, line_num)"""
    found = OrderedDict()
    # Match both _() (not preceded by another _) and __()
    pattern = re.compile(r'(?:__|(?<![_])_)\(\s*(["\'])(.*?)\1\s*\)')
    
    for filepath in sorted(glob.glob('game/**/*.rpy', recursive=True)):
        # Skip translation files
        if 'tl/' in filepath.replace('\\', '/'):
            continue
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                lines = f.readlines()
        except Exception as e:
            print(f"Warning: could not read {filepath}: {e}")
            continue
        
        rel_path = filepath.replace('\\', '/')
        for line_num, line in enumerate(lines, 1):
            for m in pattern.finditer(line):
                text = m.group(2)
                text = unquote_rpy(text)
                if text not in found:
                    found[text] = (rel_path, line_num)
    
    return found

def parse_strings_rpy(path):
    """Parse strings.rpy into dict: old_text -> (new_text, has_todo)"""
    translations = {}
    if not os.path.exists(path):
        return translations
    
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Match old/new pairs
    pattern = re.compile(
        r'^(\s*#(?:\s*TODO)?\s*[^\n]*)\n'
        r'\s*old\s+"(.*?)"\s*\n'
        r'\s*new\s+"(.*?)"\s*$',
        re.MULTILINE | re.DOTALL
    )
    
    for m in pattern.finditer(content):
        comment = m.group(1)
        old_text = unquote_rpy(m.group(2))
        new_text = unquote_rpy(m.group(3))
        has_todo = 'TODO' in comment
        translations[old_text] = (new_text, has_todo)
    
    return translations

def main():
    print("Extracting strings from source files...")
    source_strings = extract_strings()
    print(f"Found {len(source_strings)} unique strings from __() calls")
    
    print(f"Reading existing translations from {STRINGS_RPY}...")
    existing = parse_strings_rpy(STRINGS_RPY)
    print(f"Found {len(existing)} existing translation entries")
    
    # Count stats
    preserved = 0
    added_new = 0
    added_fallback = 0
    
    output_lines = [
        "# Translation file for chinese_simplified",
        "# Auto-generated by merge_translations.py",
        "",
        "translate chinese_simplified strings:",
        "",
    ]
    
    for text, (filepath, line_num) in source_strings.items():
        # Skip empty strings
        if not text:
            continue
        
        if text in existing:
            new_text, has_todo = existing[text]
            if new_text and new_text != text:
                preserved += 1
                comment = f"    # {filepath}:{line_num}"
            else:
                added_fallback += 1
                comment = f"    # TODO {filepath}:{line_num}"
            
            old_quoted = quote_for_rpy(text)
            new_quoted = quote_for_rpy(new_text if new_text else text)
            
            output_lines.append(comment)
            output_lines.append(f'    old "{old_quoted}"')
            output_lines.append(f'    new "{new_quoted}"')
            output_lines.append("")
        else:
            added_new += 1
            old_quoted = quote_for_rpy(text)
            
            output_lines.append(f"    # TODO {filepath}:{line_num}")
            output_lines.append(f'    old "{old_quoted}"')
            output_lines.append(f'    new "{old_quoted}"')
            output_lines.append("")
    
    # Backup old file
    if os.path.exists(STRINGS_RPY):
        shutil.copy2(STRINGS_RPY, BACKUP_RPY)
        print(f"Backup saved to {BACKUP_RPY}")
    
    with open(STRINGS_RPY, 'w', encoding='utf-8') as f:
        f.write('\n'.join(output_lines) + '\n')
    
    print(f"\nWritten {STRINGS_RPY}")
    print(f"  Preserved translations: {preserved}")
    print(f"  Fallback (untranslated): {added_fallback}")
    print(f"  New strings added: {added_new}")
    print(f"  Total entries: {len(source_strings)}")

if __name__ == '__main__':
    import shutil
    main()
