# TODO: Translation updated at 2026-09-11 06:39

translate chinese_simplified strings:
    old "Shaken"
    new "受惊"
    old "Normal"
    new "正常"
    old "%s was so tired that she fell sick for %i day%s"
    new "%s 劳累过度，病倒了 %i 天%s"
    old "%s is fully healed."
    new "%s 已完全康复。"
    old "%s rested in her pen today."
    new "%s 今天在圈栏里休息。"
    old "%s rested in her room today."
    new "%s 今天在房间里休息。"
    old "\n{color=[c_emerald]}She is now fully recovered and can go back to work or training.{/color}"
    new """
{color=[c_emerald]}她现已完全康复，可以回去工作或训练了。{/color}"""
    old "\n{color=[c_emerald]}She is now fully recovered and can go back to work as a %s.{/color}"
    new """
{color=[c_emerald]}她现已完全康复，可以作为 %s 回去工作了。{/color}"""
    old "\n{color=[c_emerald]}She is now fully recovered and went back to resting.{/color}"
    new """
{color=[c_emerald]}她现已完全康复，继续休息。{/color}"""
    old "\n{color=[c_emerald]}She is now fully rested and can go back to her training.{/color}"
    new """
{color=[c_emerald]}她现已充分休息，可以继续训练了。{/color}"""
    old "\n{color=[c_emerald]}She is now fully rested and can go back to work as a %s.{/color}"
    new """
{color=[c_emerald]}她现已充分休息，可以作为 %s 回去工作了。{/color}"""
    old "\n{color=[c_emerald]}She is now fully rested and is waiting for a job assignment.{/color}"
    new """
{color=[c_emerald]}她现已充分休息，正在等待工作安排。{/color}"""

