# TODO: Translation updated at 2026-09-11 06:39

translate chinese_simplified strings:
    old "%s is {b}away{/b} on a class or quest for %s more day%s."
    new "%s {b}外出{/b}上课或执行任务，还需 %s 天%s。"
    old "%s is {b}resting{/b} in her pen today."
    new "%s 今天在圈栏里{b}休息{/b}。"
    old "%s is being trained at the {b}farm{/b} (%s training)."
    new "%s 正在{b}农场{/b}接受训练（%s 训练）。"
    old "%s is {b}resting{/b} today as scheduled."
    new "%s 今天按安排{b}休息{/b}。"
    old "%s is {b}resting{/b} today."
    new "%s 今天{b}休息{/b}。"
    old "%s's energy is low. She will be automatically sent to {b}rest{/b} today."
    new "%s 的精力不足，今天将被自动送去{b}休息{/b}。"
    old "%s is working a {b}half-shift{/b} today."
    new "%s 今天上{b}半个班次{/b}。"
    old "%s is set to train in the {b}master bedroom{/b}."
    new "%s 被安排在{b}主卧{/b}训练。"
    old "%s is ready to {b}rank up{/b}."
    new "%s 已准备好{b}提升品级{/b}。"
    old "%s is ready to {b}level up{/b}."
    new "%s 已准备好{b}升级{/b}。"
    old "%s is {b}hurt or sick{/b} and will need to rest for 1 more day before she can do anything."
    new "%s {b}受伤或生病{/b}了，需要再休息 1 天才能行动。"
    old "%s is {b}hurt or sick{/b} and will need to rest for %s more days until she can do anything."
    new "%s {b}受伤或生病{/b}了，需要再休息 %s 天才能行动。"
    old "%s is {b}tired{/b} and needs to be fully rested until she can work again."
    new "%s 现在{b}疲劳{/b}，必须充分休息后才能重新工作。"
    old "%s is {b}working and whoring{/b} today."
    new "%s 今天{b}工作并接客{/b}。"
    old "%s is not {b}working and whoring{/b}."
    new "%s 没有{b}工作并接客{/b}。"
    old "%s will remain {b}naked{/b} at all times."
    new "%s 将始终维持{b}裸体{/b}。"
    old "%s will remain {b}naked{/b} today."
    new "%s 今天将维持{b}裸体{/b}。"
    old "%s is not {b}naked{/b} (and that's a problem for you, apparently)."
    new "%s 没有{b}裸体{/b}（而这显然让你很不满）。"
    old "You know that %s has a {b}negative fixation{/b}."
    new "你知道 %s 有一个{b}负面执念{/b}。"
    old "Ready to {b}rank up{/b}"
    new "可以{b}提升品级{/b}"
    old "Ready to {b}level up{/b}"
    new "可以{b}升级{/b}"
    old "{b}Hurt{/b} for %s day%s"
    new "{b}受伤{/b} %s 天%s"
    old "{b}Exhausted{/b}"
    new "{b}精疲力竭{/b}"
    old "{b}Away{/b} on a class or quest for %s day%s"
    new "{b}外出{/b} %s 天%s（上课或任务）"
    old "Training at the {b}farm{/b}"
    new "正在{b}农场{/b}训练"
    old "{b}Resting today{/b}"
    new "{b}今日休息{/b}"
    old "{b}Half-shift{/b}"
    new "{b}半个班次{/b}"
    old "{b}Working and whoring{/b}"
    new "{b}工作并接客{/b}"
    old "{b}Naked{/b}"
    new "{b}裸体{/b}"
    old "Has a {b}negative fixation{/b}"
    new "有{b}负面执念{/b}"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "No sex acts available for whoring"
    new "没有可用于接客的性行为"
    old "Libido/Obedience too low"
    new "性欲/服从太低"

