# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old """
%s"""
    new " %s"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "OFF"
    new "关"
    old "ON"
    new "开"
    old "Other"
    new "其他"
    old "Activate or deactivate objectionable content (won't affect story scenes)."
    new "开启或关闭不良内容（不影响剧情场景）。"
    old "Choose what to do when a girlpack is missing pictures with a given tag."
    new "当女孩包缺少某个标签的图片时，选择处理方式。"
    old "Use another picture from the girl pack"
    new "使用女孩包中的其他图片"
    old "Use default pictures"
    new "使用默认图片"
    old "The game will pick a picture from the same girlpack with the closest possible tag (e.g. 'service' instead of 'handjob')."
    new "游戏会从同一女孩包中挑选标签最接近的图片（例如用“服务”代替“手交”）。"
    old "The game will pick a default picture with the proper tag."
    new "游戏会挑选标签正确的默认图片。"
    old "Choose what to do when a girlpack has low picture variety on a given tag (less than %s)."
    new "当女孩包某个标签的图片数量不足（少于 %s）时，选择处理方式。"
    old "Only use girl pack pictures"
    new "只使用女孩包图片"
    old "Mix default and girl pack pictures"
    new "混合使用默认图片和女孩包图片"
    old "The game will use only the girlpack pictures that are in the pool, at the risk of repetition."
    new "游戏只使用图片库中的女孩包图片，但有重复的风险。"
    old "The game will add some default pictures to the pool for variety."
    new "游戏会向图片库中添加一些默认图片以增加多样性。"
    old "Choose the priorities when generating pictures for advanced training."
    new "选择为高级训练生成图片时的优先级。"
    old "Variety over accuracy"
    new "多样性优先于准确性"
    old "Accuracy over variety"
    new "准确性优先于多样性"
    old "The game will prioritize picture variety over accurate tagging."
    new "游戏会优先考虑图片多样性，而非标签的准确匹配。"
    old "The game will prioritize accurate tagging over picture variety."
    new "游戏会优先考虑标签的准确匹配，而非图片多样性。"
    old "Choose the behavior of group and bisexual pictures"
    new "选择群交和双性恋图片的行为方式"
    old "Group sex: Only use group pictures"
    new "群交：只使用群交图片"
    old "Mix group pictures with regular pictures"
    new "群交图片与普通图片混合使用"
    old "The game will only pick pictures featuring a group."
    new "游戏只会选择包含群体的图片。"
    old "The game will sometimes pick normal pictures for variety."
    new "游戏有时会为了多样性选择普通图片。"
    old "Bisexual sex: Only use bisexual pictures"
    new "双性恋：只使用双性恋图片"
    old "Mix bisexual pictures with regular pictures"
    new "双性恋图片与普通图片混合使用"
    old "Choose the behavior of profile pictures outside of the 'Girls' tab."
    new "选择“女孩”页签之外的个人资料图片行为。"
    old "Slavemarket: No naked pictures."
    new "奴隶市场：不显示裸照。"
    old "Slavemarket: Allow naked pictures."
    new "奴隶市场：允许显示裸照。"
    old "The slavemarket may not display naked profile pictures."
    new "奴隶市场不会显示裸体个人资料图片。"
    old "The slavemarket may display naked pictures."
    new "奴隶市场可以显示裸体图片。"
    old "City: No naked pictures."
    new "城市：不显示裸照。"
    old "City: Allow naked pictures."
    new "城市：允许显示裸照。"
    old "Free girls may not display naked profile pictures."
    new "自由女孩不显示裸体个人资料图片。"
    old "Free girls may display naked pictures ('Naturist' trait)."
    new "自由女孩可以显示裸体图片（“天体主义者”特质）。"
    old "Allow extended tags for jobs and sex acts."
    new "为工作和性行为启用扩展标签。"
    old "Jobs: Narrow tagging"
    new "工作：窄标签"
    old "Jobs: Extended tagging"
    new "工作：扩展标签"
    old "Job pictures will only look for accurate tags (e.g. 'masseuse' for masseuse)."
    new "工作图片只查找精确匹配的标签（例如按摩师对应“按摩师”）。"
    old "Job pictures will extend the search to 'close enough' tags (e.g. 'swimsuit' for masseuse)."
    new "工作图片会把搜索扩展到“足够接近”的标签（例如按摩师对应“泳装”）。"
    old "Sex acts: Narrow tagging"
    new "性行为：窄标签"
    old "Sex acts: Extended tagging"
    new "性行为：扩展标签"
    old "Sex pictures will only look for accurate tags (e.g. 'toy' for fetish)."
    new "色情图片只查找精确匹配的标签（例如恋物对应“玩具”）。"
    old "Job pictures will extend the search to 'close enough' tags (e.g. 'machine' for fetish)."
    new "工作图片会把搜索扩展到“足够接近”的标签（例如恋物对应“机器”）。"
    old "Display 'news' notifications next the home screen's buttons."
    new "在主页按钮旁显示“新闻”通知。"
    old "Flashing notifications"
    new "闪烁通知"
    old "Static notifications"
    new "静态通知"
    old "No notifications"
    new "无通知"
    old "Display a flashing notification until you hover the mouse over it (default)."
    new "显示闪烁通知，直到你用鼠标悬停（默认）。"
    old "Display a static notification."
    new "显示静态通知。"
    old "Display no notification."
    new "不显示任何通知。"
    old "Use a scrollable screen or numbered tabs to browse the 'Girls' screen (tabs may improve performance)."
    new "使用可滚动屏幕或编号页签浏览“女孩”界面（页签可能提升性能）。"
    old "Scroll girls"
    new "滚动浏览女孩"
    old "Use tabs"
    new "使用页签"
    old "Display girls on a signle scrollable screen (legacy mode: may decrease performance)."
    new "在单个可滚动屏幕上显示女孩（旧模式：可能降低性能）。"
    old "Display girls with numbered tabs (may improve performance)."
    new "以编号页签显示女孩（可提升性能）。"
    old "Display girlpack rating on girl profiles"
    new "在女孩资料页显示女孩包评分"
    old "Never"
    new "从不"
    old "In slavemarket"
    new "在奴隶市场"
    old "In slavemarket/City"
    new "在奴隶市场/城市"
    old "Everywhere"
    new "无处不在"
    old "Never display girlpack rating on profile."
    new "从不在资料页显示女孩包评分。"
    old "Display rating on profile in slavemarket only."
    new "仅在奴隶市场的资料页显示评分。"
    old "Display rating on profile in slavemarket and city."
    new "在奴隶市场和城市的资料页显示评分。"
    old "Always display rating on profile."
    new "始终在资料页显示评分。"
    old "Preview when hovering"
    new "悬停时预览"
    old "Do not preview girls"
    new "不预览女孩"
    old "Preview girls"
    new "预览女孩"
    old "You will not see a girl's profile when hovering over her button."
    new "悬停在女孩按钮上时，你不会看到她的资料页。"
    old "You will see a girl's profile when hovering over her button."
    new "悬停在女孩按钮上时，你会看到她的资料页。"
    old "Do not preview quests/classes"
    new "不预览课程/任务"
    old "Preview quests/classes"
    new "预览课程/任务"
    old "You will not see a class or quest's profile when hovering over its button."
    new "悬停在课程或任务按钮上时，你不会看到它的资料页。"
    old "You will see a class or quest's profile when hovering over its button."
    new "悬停在课程或任务按钮上时，你会看到它的资料页。"
    old "Display optional status icons on girl portraits."
    new "在女孩头像上显示可选状态图标。"
    old "Display sanity with a girl's mood."
    new "在女孩心情旁显示理智值。"
    old "In farm only"
    new "仅在农场"
    old "Sanity will only display when a girl is at the farm."
    new "理智值只在女孩位于农场时显示。"
    old "Sanity will be displayed on the 'Mood' recap."
    new "理智值将显示在“心情”汇总中。"
    old "Choose how to edit badge settings for your girls."
    new "选择为女孩编辑徽章设置的方式。"
    old "On profile only"
    new "仅在资料页"
    old "On profile and portrait"
    new "在资料页和头像上"
    old "Click on a badge in the girl's profile to change it."
    new "点击女孩资料页中的徽章即可更改。"
    old "Click on a badge in the girl's profile or portrait to change it."
    new "点击女孩资料页或头像上的徽章即可更改。"
    old "Hide events during the 'End Day' loop."
    new "在“结束一天”循环中隐藏事件。"
    old "Allow skipping during the 'End Day' loop."
    new "允许在“结束一天”循环中跳过。"
    old "Reports: Not skippable"
    new "报告：不可跳过"
    old "Reports: Skippable"
    new "报告：可跳过"
    old "Skipping matchmaking and satisfaction reports with 'Ctrl' is not possible."
    new "无法用“Ctrl”跳过配对和满意度报告。"
    old "Skipping matchmaking and satisfaction reports with 'Ctrl' is possible."
    new "可以用“Ctrl”跳过配对和满意度报告。"
    old "Nightly recap: Not skippable"
    new "夜间汇总：不可跳过"
    old "Nightly recap: Skippable"
    new "夜间汇总：可跳过"
    old "Skipping the nightly recap with 'Ctrl' is not possible."
    new "无法用“Ctrl”跳过夜间汇总。"
    old "Skipping the nightly recap with 'Ctrl' is possible."
    new "可以用“Ctrl”跳过夜间汇总。"
    old "Choose display mode for 'End Day' events (WIP)."
    new "选择“结束一天”事件的显示模式（制作中）。"
    old "Light mode"
    new "浅色模式"
    old "Dark mode"
    new "深色模式"
    old "End day events are presented in light mode."
    new "结束一天事件以浅色模式呈现。"
    old "End day events are presented in dark mode."
    new "结束一天事件以深色模式呈现。"
    old "Define naming options for non-original girls ('clones')."
    new "为非原版女孩（“克隆体”）定义命名选项。"
    old "Randomize first name"
    new "随机名字"
    old "Keep first name"
    new "保留名字"
    old "First name will be randomized for non-original girls."
    new "非原版女孩的名字将被随机化。"
    old "First name will be remain the same as the original for non-original girls."
    new "非原版女孩的名字将与原版保持一致。"
    old "Randomize last name"
    new "随机姓氏"
    old "Keep last name"
    new "保留姓氏"
    old "Last name will be randomized for non-original girls."
    new "非原版女孩的姓氏将被随机化。"
    old "Last name will be remain the same as the original for non-original girls."
    new "非原版女孩的姓氏将与原版保持一致。"
    old "Prioritize girlpack settings"
    new "女孩包设置优先"
    old "Prioritize in-game settings"
    new "游戏内设置优先"
    old "The girlpack's _BK.ini settings will take precedence over the settings above."
    new "女孩包的 _BK.ini 设置将优先于上述设置。"
    old "The settings above will take precedence over the girlpack's _BK.ini settings."
    new "上述设置将优先于女孩包的 _BK.ini 设置。"
    old "Bestiality"
    new "兽交"
    old "Monsters/Tentacles"
    new "怪物/触手"
    old "Machines"
    new "机械"
    old "Away on a class or quest."
    new "外出上课或执行任务。"
    old "Training/Resting at the farm."
    new "在农场训练/休息。"
    old "Scheduled to rest."
    new "被安排休息。"
    old "On a half-shift."
    new "上半个班次。"
    old "Training in the Master's bedroom."
    new "在主人的卧室里训练。"
    old "Negative fixation discovered."
    new "发现了负面癖好。"
    old "Currently naked."
    new "当前为裸体。"
    old "Currently not naked."
    new "当前非裸体。"
    old "Set to work and whore."
    new "被安排工作并接客。"
    old "Not set to work and whore"
    new "未被安排工作并接客"
    old "Normal events"
    new "普通事件"
    old "Matchmaking"
    new "配对"
    old "Matchmaking reports"
    new "配对报告"
    old "Customer special events"
    new "顾客特殊事件"
    old "Level/Job/Rank up"
    new "升级/职业晋升/等阶提升"
    old "Level up, Job up and Rank up notifications"
    new "升级、职业晋升和等阶提升通知"
    old "Health/Security"
    new "健康/安保"
    old "Health and security events"
    new "健康与安保事件"
    old "Customer satisfaction report"
    new "顾客满意度报告"
    old "Farm events"
    new "农场事件"
    old "Resting events"
    new "休息事件"
    old " will be shown."
    new " 将显示。"
    old " will be hidden."
    new " 将隐藏。"

