# TODO: Translation updated at 2026-06-12 09:06

translate chinese_simplified strings:
    old "Self-voicing disabled."
    new "自动语音已禁用。"
    old "Clipboard voicing enabled. "
    new "剪贴板语音已启用。"
    old "Self-voicing enabled. "
    new "自动语音已启用。"
    old "bar"
    new "进度条"
    old "selected"
    new "已选中"
    old "viewport"
    new "视口"
    old "horizontal scroll"
    new "水平滚动"
    old "vertical scroll"
    new "垂直滚动"
    old "activate"
    new "激活"
    old "deactivate"
    new "停用"
    old "increase"
    new "增加"
    old "decrease"
    new "减少"
    old "Accessibility Menu. Use up and down arrows to navigate, and enter to activate buttons and bars."
    new "无障碍菜单。使用上下方向键进行导航，按回车键激活按钮和进度条。"
    old "Font Override"
    new "字体覆盖"
    old "Default"
    new "默认"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "文字大小缩放"
    old "Reset"
    new "重置"
    old "Line Spacing Scaling"
    new "行距缩放"
    old "High Contrast Text"
    new "高对比度文字"
    old "Enable"
    new "启用"
    old "Disable"
    new "禁用"
    old "Self-Voicing"
    new "自动语音"
    old "Off"
    new "关闭"
    old "Text-to-speech"
    new "文字转语音"
    old "Clipboard"
    new "剪贴板"
    old "Debug"
    new "调试"
    old "Self-Voicing Volume Drop"
    new "自动语音音量降低"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "此菜单中的选项旨在提高无障碍性。它们可能无法在所有游戏中使用，某些选项组合可能会导致游戏无法运行。这不是游戏或引擎的问题。为了在更改字体时获得最佳效果，请尽量保持文字大小与原始大小相同。"
    old "{#weekday}Monday"
    new "{#weekday}星期一"
    old "{#weekday}Tuesday"
    new "{#weekday}星期二"
    old "{#weekday}Wednesday"
    new "{#weekday}星期三"
    old "{#weekday}Thursday"
    new "{#weekday}星期四"
    old "{#weekday}Friday"
    new "{#weekday}星期五"
    old "{#weekday}Saturday"
    new "{#weekday}星期六"
    old "{#weekday}Sunday"
    new "{#weekday}星期日"
    old "{#weekday_short}Mon"
    new "{#weekday_short}周一"
    old "{#weekday_short}Tue"
    new "{#weekday_short}周二"
    old "{#weekday_short}Wed"
    new "{#weekday_short}周三"
    old "{#weekday_short}Thu"
    new "{#weekday_short}周四"
    old "{#weekday_short}Fri"
    new "{#weekday_short}周五"
    old "{#weekday_short}Sat"
    new "{#weekday_short}周六"
    old "{#weekday_short}Sun"
    new "{#weekday_short}周日"
    old "{#month}January"
    new "{#month}一月"
    old "{#month}February"
    new "{#month}二月"
    old "{#month}March"
    new "{#month}三月"
    old "{#month}April"
    new "{#month}四月"
    old "{#month}May"
    new "{#month}五月"
    old "{#month}June"
    new "{#month}六月"
    old "{#month}July"
    new "{#month}七月"
    old "{#month}August"
    new "{#month}八月"
    old "{#month}September"
    new "{#month}九月"
    old "{#month}October"
    new "{#month}十月"
    old "{#month}November"
    new "{#month}十一月"
    old "{#month}December"
    new "{#month}十二月"
    old "{#month_short}Jan"
    new "{#month_short}1月"
    old "{#month_short}Feb"
    new "{#month_short}2月"
    old "{#month_short}Mar"
    new "{#month_short}3月"
    old "{#month_short}Apr"
    new "{#month_short}4月"
    old "{#month_short}May"
    new "{#month_short}5月"
    old "{#month_short}Jun"
    new "{#month_short}6月"
    old "{#month_short}Jul"
    new "{#month_short}7月"
    old "{#month_short}Aug"
    new "{#month_short}8月"
    old "{#month_short}Sep"
    new "{#month_short}9月"
    old "{#month_short}Oct"
    new "{#month_short}10月"
    old "{#month_short}Nov"
    new "{#month_short}11月"
    old "{#month_short}Dec"
    new "{#month_short}12月"
    old "%b %d, %H:%M"
    new "%b %d, %H:%M"
    old "Save slot %s: [text]"
    new "保存栏位 %s: [text]"
    old "Load slot %s: [text]"
    new "读取栏位 %s: [text]"
    old "Delete slot [text]"
    new "删除栏位 [text]"
    old "File page auto"
    new "自动存档页"
    old "File page quick"
    new "快速存档页"
    old "File page [text]"
    new "存档页 [text]"
    old "Next file page."
    new "下一存档页。"
    old "Previous file page."
    new "上一存档页。"
    old "Quick save complete."
    new "快速保存完成。"
    old "Quick save."
    new "快速保存。"
    old "Quick load."
    new "快速读取。"
    old "Language [text]"
    new "语言 [text]"
    old "Open [text] directory."
    new "打开 [text] 目录。"
    old "The interactive director is not enabled here."
    new "互动导演在此未启用。"
    old "⬆"
    new "⬆"
    old "⬇"
    new "⬇"
    old "Done"
    new "完成"
    old "(statement)"
    new "(语句)"
    old "(tag)"
    new "(标签)"
    old "(attributes)"
    new "(属性)"
    old "(transform)"
    new "(变换)"
    old "(transition)"
    new "(过渡)"
    old "(channel)"
    new "(声道)"
    old "(filename)"
    new "(文件名)"
    old "Change"
    new "更改"
    old "Add"
    new "添加"
    old "Remove"
    new "移除"
    old "Statement:"
    new "语句："
    old "Tag:"
    new "标签："
    old "Attributes:"
    new "属性："
    old "Click to toggle attribute, right click to toggle negative attribute."
    new "点击切换属性，右键点击切换否定属性。"
    old "Transforms:"
    new "变换："
    old "Click to set transform, right click to add to transform list."
    new "点击设置变换，右键点击添加到变换列表。"
    old "Customize director.transforms to add more transforms."
    new "自定义 director.transforms 以添加更多变换。"
    old "Behind:"
    new "后置："
    old "Click to set, right click to add to behind list."
    new "点击设置，右键点击添加到后置列表。"
    old "Transition:"
    new "过渡："
    old "Click to set."
    new "点击设置。"
    old "Customize director.transitions to add more transitions."
    new "自定义 director.transitions 以添加更多过渡效果。"
    old "Channel:"
    new "声道："
    old "Customize director.audio_channels to add more channels."
    new "自定义 director.audio_channels 以添加更多声道。"
    old "Audio Filename:"
    new "音频文件名："
    old "Are you sure?"
    new "你确定吗？"
    old "Are you sure you want to delete this save?"
    new "你确定要删除这个存档吗？"
    old "Are you sure you want to overwrite your save?"
    new "你确定要覆盖你的存档吗？"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new """读取将丢失未保存的进度。
你确定要这样做吗？"""
    old "Are you sure you want to quit?"
    new "你确定要退出吗？"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new """你确定要返回主菜单吗？
这将丢失未保存的进度。"""
    old "Are you sure you want to continue where you left off?"
    new "你确定要从上次离开的地方继续吗？"
    old "Are you sure you want to end the replay?"
    new "你确定要结束回放吗？"
    old "Are you sure you want to begin skipping?"
    new "你确定要开始跳过吗？"
    old "Are you sure you want to skip to the next choice?"
    new "你确定要跳到下一个选项吗？"
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new "你确定要跳过未读对话直到下一个选项吗？"
    old "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?"
    new "此存档是在不同设备上创建的。恶意构造的存档文件可能会损害你的计算机。你信任此存档的创建者以及所有可能更改过该文件的人吗？"
    old "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user."
    new "你信任创建此存档的设备吗？只有当你是该设备的唯一用户时，才应选择是。"
    old "Failed to save screenshot as %s."
    new "截图保存失败 %s。"
    old "Saved screenshot as %s."
    new "截图已保存为 %s。"
    old "Skip Mode"
    new "跳过模式"
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new "本程序包含基于多种许可证（包括 MIT 许可证和 GNU 宽通用公共许可证）的免费软件。完整软件列表（包括完整源代码链接）可以在{a=https://www.renpy.org/l/license}这里{/a}找到。"
    old "display"
    new "显示"
    old "transitions"
    new "过渡效果"
    old "skip transitions"
    new "跳过过渡效果"
    old "video sprites"
    new "视频精灵"
    old "show empty window"
    new "显示空窗口"
    old "text speed"
    new "文字速度"
    old "joystick"
    new "手柄"
    old "joystick..."
    new "手柄..."
    old "skip"
    new "跳过"
    old "skip unseen [text]"
    new "跳过未读 [text]"
    old "skip unseen text"
    new "跳过未读文字"
    old "begin skipping"
    new "开始跳过"
    old "after choices"
    new "选项后"
    old "skip after choices"
    new "跳过选项后"
    old "auto-forward time"
    new "自动前进时间"
    old "auto-forward"
    new "自动前进"
    old "Auto forward"
    new "自动前进"
    old "auto-forward after click"
    new "点击后自动前进"
    old "automatic move"
    new "自动移动"
    old "wait for voice"
    new "等待语音"
    old "voice sustain"
    new "语音保持"
    old "self voicing"
    new "自动语音"
    old "self voicing enable"
    new "启用自动语音"
    old "self voicing disable"
    new "禁用自动语音"
    old "self voicing volume drop"
    new "自动语音音量降低"
    old "clipboard voicing"
    new "剪贴板语音"
    old "clipboard voicing enable"
    new "启用剪贴板语音"
    old "clipboard voicing disable"
    new "禁用剪贴板语音"
    old "debug voicing"
    new "调试语音"
    old "debug voicing enable"
    new "启用调试语音"
    old "debug voicing disable"
    new "禁用调试语音"
    old "emphasize audio"
    new "强调音频"
    old "rollback side"
    new "回滚侧"
    old "gl powersave"
    new "GL 省电模式"
    old "gl framerate"
    new "GL 帧率"
    old "gl tearing"
    new "GL 画面撕裂"
    old "font transform"
    new "字体变换"
    old "font size"
    new "字体大小"
    old "font line spacing"
    new "字体行距"
    old "system cursor"
    new "系统光标"
    old "renderer menu"
    new "渲染器菜单"
    old "accessibility menu"
    new "无障碍菜单"
    old "high contrast text"
    new "高对比度文字"
    old "audio when minimized"
    new "最小化时播放音频"
    old "audio when unfocused"
    new "失去焦点时播放音频"
    old "web cache preload"
    new "网页缓存预加载"
    old "voice after game menu"
    new "游戏菜单后播放语音"
    old "restore window position"
    new "恢复窗口位置"
    old "reset"
    new "重置"
    old "main volume"
    new "主音量"
    old "music volume"
    new "音乐音量"
    old "sound volume"
    new "音效音量"
    old "voice volume"
    new "语音音量"
    old "mute main"
    new "静音主音量"
    old "mute music"
    new "静音音乐"
    old "mute sound"
    new "静音音效"
    old "mute voice"
    new "静音语音"
    old "mute all"
    new "全部静音"
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new "剪贴板语音已启用。按 'shift+C' 禁用。"
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new "自动语音会朗读 \"[renpy.display.tts.last]\"。按 'alt+shift+V' 禁用。"
    old "Self-voicing enabled. Press 'v' to disable."
    new "自动语音已启用。按 'v' 禁用。"
    old "Speech Bubble Editor"
    new "对话气泡编辑器"
    old "(hide)"
    new "(隐藏)"
    old "(clear retained bubbles)"
    new "(清除保留的气泡)"
    old "Sync downloaded."
    new "同步已下载。"
    old "Could not connect to the Ren'Py Sync server."
    new "无法连接到 Ren'Py 同步服务器。"
    old "The Ren'Py Sync server timed out."
    new "Ren'Py 同步服务器超时。"
    old "An unknown error occurred while connecting to the Ren'Py Sync server."
    new "连接 Ren'Py 同步服务器时发生未知错误。"
    old "The Ren'Py Sync server does not have a copy of this sync. The sync ID may be invalid, or it may have timed out."
    new "Ren'Py 同步服务器没有此同步的副本。同步 ID 可能无效，或可能已超时。"
    old "Please enter the sync ID you generated.\nNever enter a sync ID you didn't create yourself."
    new """请输入你生成的同步 ID。
切勿输入非你自己创建的同步 ID。"""
    old "The sync ID is not in the correct format."
    new "同步 ID 格式不正确。"
    old "The sync could not be decrypted."
    new "同步无法解密。"
    old "The sync belongs to a different game."
    new "同步属于不同的游戏。"
    old "The sync contains a file with an invalid name."
    new "同步包含文件名无效的文件。"
    old "This will upload your saves to the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}.\nDo you want to continue?"
    new """这将把您的存档上传到{a=https://sync.renpy.org}Ren'Py 同步服务器{/a}。
你要继续吗？"""
    old "Enter Sync ID"
    new "输入同步 ID"
    old "This will contact the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}."
    new "这将连接{a=https://sync.renpy.org}Ren'Py 同步服务器{/a}。"
    old "Sync Success"
    new "同步成功"
    old "The Sync ID is:"
    new "同步 ID 为："
    old "You can use this ID to download your save on another device.\nThis sync will expire in an hour.\nRen'Py Sync is supported by {a=https://www.renpy.org/sponsors.html}Ren'Py's Sponsors{/a}."
    new """你可以使用此 ID 在另一台设备上下载你的存档。
此同步将在一小时后过期。
Ren'Py 同步由{a=https://www.renpy.org/sponsors.html}Ren'Py 的赞助商{/a}提供支持。"""
    old "Sync Error"
    new "同步错误"
    old "Contacting App Store\nPlease Wait..."
    new """正在连接应用商店
请稍候..."""
    old "No update methods found."
    new "未找到更新方法。"
    old "Could not download file list: "
    new "无法下载文件列表："
    old "File list digest does not match."
    new "文件列表摘要不匹配。"
    old "An error is being simulated."
    new "正在模拟错误。"
    old "Either this project does not support updating, or the update status file was deleted."
    new "此项目不支持更新，或更新状态文件已被删除。"
    old "This account does not have permission to perform an update."
    new "此账户没有执行更新的权限。"
    old "This account does not have permission to write the update log."
    new "此账户没有写入更新日志的权限。"
    old "Could not verify update signature."
    new "无法验证更新签名。"
    old "The update file was not downloaded."
    new "更新文件未下载。"
    old "The update file does not have the correct digest - it may have been corrupted."
    new "更新文件的摘要不正确 - 可能已损坏。"
    old "While unpacking {}, unknown type {}."
    new "解压 {} 时，未知类型 {}。"
    old "Updater"
    new "更新器"
    old "An error has occured:"
    new "发生错误："
    old "Checking for updates."
    new "正在检查更新。"
    old "This program is up to date."
    new "此程序已是最新版本。"
    old "[u.version] is available. Do you want to install it?"
    new "[u.version] 已可用。你想安装它吗？"
    old "Preparing to download the updates."
    new "正在准备下载更新。"
    old "Downloading the updates."
    new "正在下载更新。"
    old "Unpacking the updates."
    new "正在解压更新。"
    old "Finishing up."
    new "正在完成。"
    old "The updates have been installed. The program will restart."
    new "更新已安装。程序将重新启动。"
    old "The updates have been installed."
    new "更新已安装。"
    old "The updates were cancelled."
    new "更新已取消。"
    old "Preparing to download the game data."
    new "正在准备下载游戏数据。"
    old "Downloading the game data."
    new "正在下载游戏数据。"
    old "The game data has been downloaded."
    new "游戏数据已下载。"
    old "An error occured when trying to download game data:"
    new "尝试下载游戏数据时发生错误："
    old "This game cannot be run until the game data has been downloaded."
    new "在游戏数据下载完成之前，无法运行此游戏。"
    old "Retry"
    new "重试"
    old "Renderer"
    new "渲染器"
    old "Automatically Choose"
    new "自动选择"
    old "Force GL Renderer"
    new "强制 GL 渲染器"
    old "Force ANGLE Renderer"
    new "强制 ANGLE 渲染器"
    old "Force GLES Renderer"
    new "强制 GLES 渲染器"
    old "Force GL2 Renderer"
    new "强制 GL2 渲染器"
    old "Force ANGLE2 Renderer"
    new "强制 ANGLE2 渲染器"
    old "Force GLES2 Renderer"
    new "强制 GLES2 渲染器"
    old "Enable (No Blocklist)"
    new "启用（无阻止列表）"
    old "Powersave"
    new "省电模式"
    old "Framerate"
    new "帧率"
    old "Screen"
    new "屏幕"
    old "60"
    new "60"
    old "30"
    new "30"
    old "Tearing"
    new "撕裂"
    old "Changes will take effect the next time this program is run."
    new "更改将在下次运行此程序时生效。"
    old "Performance Warning"
    new "性能警告"
    old "This computer is using software rendering."
    new "此计算机正在使用软件渲染。"
    old "This game requires use of GL2 that can't be initialised."
    new "此游戏需要使用无法初始化的 GL2。"
    old "This computer has a problem displaying graphics: [problem]."
    new "此计算机显示图形时出现问题：[problem]。"
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "其图形驱动程序可能已过期或未正常运行。这可能导致图形显示缓慢或错误。"
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new "{a=edit:1:log.txt}log.txt{/a} 文件可能包含帮助你确定计算机问题的信息。"
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new "有关如何修复此问题的更多详细信息，请参阅{a=[url]}文档{/a}。"
    old "Continue, Show this warning again"
    new "继续，下次显示此警告"
    old "Continue, Don't show warning again"
    new "继续，不再显示警告"
    old "Change render options"
    new "更改渲染选项"
    old "Select Gamepad to Calibrate"
    new "选择要校准的手柄"
    old "No Gamepads Available"
    new "无可用手柄"
    old "Calibrating [name] ([i]/[total])"
    new "正在校准 [name] ([i]/[total])"
    old "Press or move the '[control!s]' [kind]."
    new "按下或移动 '[control!s]' [kind]。"
    old "Skip (A)"
    new "跳过 (A)"
    old "Back (B)"
    new "返回 (B)"
    old "Open"
    new "打开"
    old "Opens the traceback.txt file in a text editor."
    new "在文本编辑器中打开 traceback.txt 文件。"
    old "Copy BBCode"
    new "复制 BBCode"
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new "将 traceback.txt 文件作为 BBcode 复制到剪贴板，用于 https://lemmasoft.renai.us/ 等论坛。"
    old "Copy Markdown"
    new "复制 Markdown"
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new "将 traceback.txt 文件作为 Markdown 复制到剪贴板，用于 Discord。"
    old "An exception has occurred."
    new "发生异常。"
    old "Rollback"
    new "回滚"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "尝试回滚到之前的时间，允许你保存或选择不同的选项。"
    old "Ignores the exception, allowing you to continue."
    new "忽略异常，允许你继续。"
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "忽略异常，允许你继续。这通常会导致额外的错误。"
    old "Reload"
    new "重新加载"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "从磁盘重新加载游戏，如果可能的话保存并恢复游戏状态。"
    old "Console"
    new "控制台"
    old "Opens a console to allow debugging the problem."
    new "打开控制台以调试问题。"
    old "Quits the game."
    new "退出游戏。"
    old "Parsing the script failed."
    new "解析脚本失败。"

