# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "[session.session_name] — Day [session.date]"
    new "[session.session_name] — 第 [session.date] 天"
    old "[auction_display_bid] gold"
    new "[auction_display_bid] 金币"

# TODO: Translation updated at 2026-09-25 05:57

translate chinese_simplified strings:
    old "Committed: [auction_committed]"
    new "已占用: [auction_committed]"
    old "This is your own lot — you cannot bid on it. If it sells, the proceeds are yours; if not, it comes back to you."
    new "这是你自己的拍品——无法对其出价。若售出，货款归你；若流拍，商品原物退还。"
    old "+10"
    new "+10"
    old "+50"
    new "+50"
    old "Not enough gold — you have [auction_committed] gold committed on other lots."
    new "金币不足——你已在其他拍品上占用了 [auction_committed] 金币。"

# TODO: Translation updated at 2026-09-25 06:56

translate chinese_simplified strings:
    old "Bidders"
    new "竞买人"
    old "No bidders have taken a seat yet."
    new "还没有竞买人入座。"
    old "%d gold"
    new "%d 金币"
    old "Spent: %d"
    new "已花费：%d"
    old "Holding: %d"
    new "占用中：%d"
    old "Won: %s"
    new "已获得：%s"
    old "Budget: %d — Max premium: x%.2f — Base chance: %d%%"
    new "预算：%d — 溢价上限：x%.2f — 基础概率：%d%%"
    old "Wait for other bids"
    new "等待他人出价"
    old "Buy Insider's Ledger (%d gold)"
    new "购买《内行账本》（%d 金币）"
    old "Gavel (finalize)"
    new "落锤（结拍）"
    old "Pass (going once)"
    new "跳过（第一次提醒）"
    old "Rank [girl.rank] — Level [girl.level]"
    new "阶级 [girl.rank] — 等级 [girl.level]"
    old "Charm: [girl.char]"
    new "魅力：[girl.char]"
    old "Beauty: [girl.beauty]"
    new "容貌：[girl.beauty]"
    old "Body: [girl.body]"
    new "身材：[girl.body]"
    old "Refinement: [girl.refinement]"
    new "气质：[girl.refinement]"
    old "Sensitivity: [girl.sensitivity]"
    new "敏感：[girl.sensitivity]"
    old "Libido: [girl.libido]"
    new "性欲：[girl.libido]"
    old "Constitution: [girl.constitution]"
    new "体质：[girl.constitution]"
    old "Obedience: [girl.obedience]"
    new "服从：[girl.obedience]"

