# TODO: Translation updated at 2026-06-12 05:03

translate chinese_simplified strings:
    old "Export hardcoded data to JSON (Evolution)"
    new "将硬编码数据导出为 JSON（Evolution）"
    old "Would you like to see the intro?"
    new "你想看看开头部分吗？"
    old "You have activated a challenge. You cannot start at a later chapter if you want to complete the challenge."
    new "你已激活一项挑战。如果你想完成这项挑战，就不能从后面的章节开始。"
    old "The Slums are located on the outskirts of Zan..."
    new "贫民窟位于赞恩郊区……"
    old "The docks are home to rowdy sailors..."
    new "码头是喧闹水手们的聚集地……"
    old "The warehouse is the industrial part of Zan..."
    new "该仓库是赞恩的工业区……"
    old "The gardens are where the magic-wielding locals..."
    new "花园是当地会使用魔法的人居住的地方……"
    old "The Cathedra is the holy center..."
    new "主教座堂是神圣的中心……"
    old "This is the center of power in Zan..."
    new "这里是赞恩的权力中心……"
translate chinese_simplified init_game_38728340:

    # centered "Loading...{nw}"
    centered "加载中……{nw}"

translate chinese_simplified strings:

    # game/core/init/start.rpy:39
    old "Choose a starting mode"
    new "选择起始模式"

    # game/core/init/start.rpy:60
    old "Data export completed. Restart game to see changes."
    new "数据导出完成。重启游戏以查看更改。"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "Strange man"
    new "陌生男子"
    old "Captain Farah"
    new "法拉队长"
    old "Lieutenant"
    new "中尉"
    old "Voice"
    new "声音"
    old "Shadow"
    new "影子"
    old "Elf girl"
    new "精灵女孩"
    old "Woman slaver"
    new "女人贩子"
    old "Strange girl"
    new "陌生女孩"
    old "Market girl"
    new "市场女孩"
    old "Mysterious woman"
    new "神秘女子"
    old "Sweet girl"
    new "甜美女孩"
    old "Tough girl"
    new "彪悍女孩"
    old "Wild girl"
    new "野性女孩"
    old "Nerdy girl"
    new "书呆子女孩"
    old "Happy tailor"
    new "快活的裁缝"
    old "Quiet tailor"
    new "沉默的裁缝"
    old "Freelancer"
    new "自由佣兵"
    old "Female knight"
    new "女骑士"
    old "Noble lady"
    new "贵族小姐"
    old "Blue-haired girl"
    new "蓝发女孩"
    old "Elegant woman"
    new "优雅女子"
    old "Petite Kunoichi"
    new "娇小女忍"
    old "Elegant Kunoichi"
    new "优雅女忍"
    old "Athletic Kunoichi"
    new "运动型女忍"
    old "Talking sword"
    new "会说话的剑"
    old "Mage Girl"
    new "法师女孩"

