# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old "Search tags: %s"
    new "搜索标签：%s"
    old "AND tags: %s"
    new "AND 标签：%s"
    old "AND NOT tags: %s"
    new "并且不是标签：%s"
    old "[girl.fullname] cannot work as a whore as she refuses to do any sex act."
    new "[girl.fullname] 不能从事卖淫工作，因为她拒绝进行任何性行为。"
    old "Your brothel's reputation has changed from %s to %s."
    new "你妓院的声誉已从 %s 变为 %s。"
    old "Your brothel's reputation remains stable (%s)."
    new "你的妓院声誉保持稳定（%s）。"
    old """Brothel reputation:
%s (%s)"""
    new "妓院声誉：%s (%s)"
    old "Brothel report"
    new "妓院报告"
    old "Advertising: +%s"
    new "广告：+%s"
    old "Perks: +%s"
    new "福利：+%s"
    old "Chapter modifier: %s"
    new "章节修改器：%s"
    old "Girls: %i"
    new "女孩：%i"
    old "You have %i girls in your brothel and farm."
    new "你的妓院和农场里有 %i 个女孩。"
    old "Girl report"
    new "女孩报告"
    old "You have %i girls in your brothel."
    new "你的妓院里有 %i 个女孩。"
    old "Working: %s"
    new "正在运行：%s"
    old "Working today"
    new "今天工作"
    old "Sick girls: %s"
    new "生病的女孩：%s"
    old "Got sick"
    new "生病了"
    old "Refused to work: %s"
    new "拒绝工作：%s"
    old "Refused to work"
    new "拒绝工作"
    old "Resting: %s"
    new "静息状态：%s"
    old "Away: %s"
    new "外出：%s"
    old "Away"
    new "离开"
    old "Farm: %s"
    new "农场：%s"
    old "At the Farm"
    new "在农场"
    old "Brothel closed"
    new "妓院已关闭"
    old "Customers turned away: %s"
    new "被拒之门外的顾客：%s"
    old "Reputation lost: %s"
    new "声誉损失：%s"
    old "Your brothel was so dirty that all %s customers ran away (%s reputation)"
    new "你的妓院实在太脏了，导致全部%s名客人都跑掉了（%s声望）。"
    old "%s customers turned away because the brothel looked filthy (%s reputation)"
    new "%s 的顾客因为妓院看起来肮脏（%s 的声誉）而拒绝光顾。"
    old "Customers turned away: -%s"
    new "被拒收的顾客：-%s"
    old """
Turned away: %s"""
    new "转身离开：%s"
    old "Customers: %s"
    new "顾客：%s"
    old "Customer report"
    new "客户报告"
    old "%i %s came to %s"
    new "%i %s 来到 %s"
    old "All %s customers were able to sleep with a whore."
    new "所有 %s 的顾客都能和妓女睡觉。"
    old "Unattended customers"
    new "无人照看的顾客"
    old "No "
    new "不"
    old "No more "
    new "不再"
    old "girls were available for sex and %s customers left disappointed."
    new "有女孩可提供性服务，但仍有%s名客人失望离开。"
    old "Y%i M%i D%i %s"
    new "Y%i M%i D%i %s"
    old "Total customers: %i"
    new "客户总数：%i"
    old "Entertainment (served): %s"
    new "娱乐活动（已提供）：%s"
    old "%i customers were entertained out of %i waiting customers"
    new "在%i名等待中的客人里，共有%i名客人得到了服务。"
    old "Whoring (served): %s"
    new "卖淫（已提供）：%s"
    old "%i customers were tended to by a whore out of %i waiting customers"
    new "%i 位顾客由一名妓女从 %i 位等候的顾客中挑选出来接待。"
    old "Entertainment (satisfied): %s"
    new "娱乐体验（满意）：%s"
    old "%i customers were satisfied out of %i entertained customers"
    new "%i 位顾客感到满意，%i 位顾客受到款待。"
    old "Whoring (satisfied): %s"
    new "嫖娼（满意）：%s"
    old "%i customers were satisfied out of %i whoring customers"
    new "%i 位顾客对 %i 位顾客感到满意"
    old "%s customer(s) came to your brothel. %s got attended (%s entertained), %s got laid (%s satisfied)."
    new "%s 位顾客光顾了您的妓院。%s 位顾客得到了服务（%s 位顾客得到了娱乐），%s 位顾客发生了性关系（%s 位顾客感到满意）。"
    old "Reputation: %s (%s)"
    new "信誉：%s (%s)"
    old " reputation increase from satisfied customers."
    new "客户满意度提升了公司声誉。"
    old "Brothel reputation changed from %i to %i (%s)"
    new "妓院声誉从 %i 变为 %i (%s)"
    old "End of whoring phase"
    new "卖淫阶段结束"
    old "%s and %s have become friends."
    new "%s 和 %s 成了朋友。"
    old "%s and %s have become rivals."
    new "%s 和 %s 已成为竞争对手。"
    old "%s and %s are no longer %ss."
    new "%s 和 %s 不再是 %ss。"
    old "Cleanliness: %i (%s)"
    new "清洁度：%i (%s)"
    old "Your brothel is %s"
    new "你的妓院是%s"
    old "Dirt: %s"
    new "污垢：%s"
    old "Maintenance: %s"
    new "维护：%s"
    old """
You paid {image=img_gold} %s to the bank for your loan."""
    new "您已向银行支付了 %s 的贷款款项。"
    old "You paid {image=img_gold_24} %s in brothel costs."
    new "你支付了{image=img_gold_24} %s的妓院费用。"
    old "+%i {image=tb %s}"
    new "+%i {image=tb %s}"
    old "Income: {image=img_gold_20} %s"
    new "收入：{image=img_gold_20} %s"
    old "Girls income: "
    new "女孩收入："
    old "Girl income"
    new "女孩收入"
    old "Street whores: "
    new "街头妓女："
    old "Street whores income"
    new "街头妓女的收入"
    old "Costs: "
    new "费用："
    old "* Upkeep: %i"
    new "* 维护：%i"
    old "* Advertising: %i"
    new "* 广告：%i"
    old "%i advertising girls x %i = {image=img_gold} %i"
    new "%i 广告女孩 x %i = {image=img_gold} %i"
    old "* Security: %i"
    new "* 安全性：%i"
    old "%i goons x %i = {image=img_gold} %i"
    new "%i 暴徒 x %i = {image=img_gold} %i"
    old "* Maintenance: %i"
    new "* 维护：%i"
    old "%i maids x {image=img_gold} %i = {image=img_gold} %i"
    new "%i 女仆 x {image=img_gold} %i = {image=img_gold} %i"
    old "* Loan payment: %i"
    new "* 贷款支付：%i"
    old "Perks and special effects: %s"
    new "特长和特殊效果：%s"
    old "Warning! [girl.fullname] is unhappy and grumbling about running away..."
    new "警告！[girl.fullname] 很不开心，正在抱怨要离家出走……"
    old "Warning! [girl.fullname] is getting tired..."
    new "警告！[girl.fullname] 累了……"
translate chinese_simplified end_day_98ad9d3d:

    # "System" "Label: {color=[c_red]}[lbl]{/color} doesn't exist (Custom girl: {color=[c_red]}[girl.path]{/color})."
    "System" ""

# game/core/systems/endday.rpy:1442
translate chinese_simplified end_day_ea7f72a4:

    # girl.char "[text1]){/size}"
    girl.char ""

# game/core/systems/endday.rpy:1479
translate chinese_simplified end_day_38728340:

    # centered "Loading...{nw}"
    centered "加载中……{nw}"

translate chinese_simplified strings:

    # game/core/systems/endday.rpy:265
    old "Attempt: %s"
    new "尝试：%s"

# TODO: Translation updated at 2026-09-11 06:39

translate chinese_simplified strings:
    old "A level %s %s has been retired because of wounds or damage it sustained."
    new "一头等级为 %s 的%s因伤过重而退役了。"

