# TODO: Translation updated at 2026-06-12 05:58

translate chinese_simplified strings:
    old "Do you really want to upgrade the "
    new "你真的想升级吗？"
    old "Do you really want to add a pen to the farm for "
    new "你真的想在农场里增设一个畜栏吗？"
    old "Click here to upgrade the capacity of this facility for %s gold."
    new "点击这里升级该设施处理 %s 黄金的能力。"
    old "Click here to build this facility for %s gold."
    new "点击此处花费%s金币建造该设施。"
    old "You cannot improve this facility until you get a higher brothel license."
    new "在获得更高级别的妓院许可证之前，您无法改善这家设施。"
    old "You cannot improve this facility further."
    new "该设施已无法进一步改进。"
    old "You cannot add a %s to the %s (wrong minion type)."
    new "你不能在 %s 中添加 %s（错误的 minion 类型）。"
    old "%s, a level %s %s, has joined the farm's %s."
    new "%s，一个级别 %s %s，加入了农场的 %s。"
    old "The %s is currently full."
    new "%s当前已满。"
    old "You must build the %s first."
    new "您必须先构建 %s。"
    old "Do you want to upgrade %s to rank %s for %s gold?"
    new "你想花费 %s 金币将 %s 升级到 %s 级吗？"
    old "You do not have enough money to both upgrade the %s and buy the minion."
    new "你没有足够的钱既升级%s又购买小兵。"
    old "The farm's %s has been extended and %s, a level %s %s, has joined."
    new "农场的 %s 已扩展，并且 %s，一个级别 %s %s，已加入。"
    old "That's impossible. The farm's %s is full and cannot be upgraded at the moment."
    new "无法执行。农场的%s已达到上限，目前无法继续升级。"
    old "Level %i %s"
    new "级别 %i %s"
    old "%s refused to train today, so Gizel had her work around the farm instead "
    new " %s今天拒绝训练，所以吉泽尔让她在农场干活。"
    old "(training mode: {i}%s{/i})"
    new "（训练模式：{i}%s{/i}）"
    old "%s was held at the farm today"
    new "今天在农场举行了 %s 活动。"
    old """.
"""
    new " 。"
    old "WRONG: not in training"
    new "错误：未接受培训"
    old "Do you really want to add a pen to the farm for %s gold?"
    new "你真的要花费 %s 金币为农场增加一个栏位吗？"
translate chinese_simplified strings:

    # game/core/systems/farm.rpy:21
    old "The %s can hold %i minion%s (currently: %i). "
    new "%s 可以容纳 %i 个小兵%s（当前：%i）。"

    # game/core/systems/farm.rpy:154
    old "Do you really want to upgrade the %s for %s gold?"
    new "你真的想花费 %s 金币升级 %s 吗？"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "You don't have enough gold to expand the %s! Stop wasting my time."
    new "你没有足够的金币来扩建%s！别浪费我的时间。"
    old "The %s cannot be extended any further."
    new "%s 无法再扩建了。"
    old "Extending the %s further would draw too much attention to us. Perhaps once you get a higher brothel license, we can grease a few palms and extend our operation?"
    new "再扩建%s会太引人注意。等你拿到更高级的青楼执照，我们就可以打点关系扩建了？"
    old "The %s has been extended and can now host %s %s."
    new "%s 已扩建，现在可以容纳 %s %s。"
    old " (max level)"
    new "（满级）"
    old " (XP: %i/%i)"
    new "（经验：%i/%i）"
    old "\n%s is broken and will be retired in %s days. "
    new """
%s 坏了，将在 %s 天后退役。 """
    old "\n%s is injured and will be retired in %s days. "
    new """
%s 受伤了，将在 %s 天后退役。 """
    old " accepted training at the farm."
    new " 接受了农场训练。"
    old "%s %s and attacked Gizel! She was forced to use her magic.\n"
    new """%s %s，袭击了 Gizel！她被迫使用了魔法。
"""
    old "%s has been injured and will be out of it for %s days."
    new "%s 受伤了，将伤停 %s 天。"
    old "%s (level %s%s) was broken in the fighting. It will be retired unless you can repair it."
    new "%s（等级 %s%s）在战斗中损坏了，除非你修好它，否则将被退役。"
    old "%s (level %s%s) was injured in the fighting. It will be retired unless you can heal it."
    new "%s（等级 %s%s）在战斗中受伤了，除非你治好它，否则将被退役。"
    old "%s %sand attacked Gizel, kicking her to the ground before she could use her magic!\n"
    new """%s %s，袭击了 Gizel，在她念咒之前就把她踢翻在地！
"""
    old "%s ran away into the night."
    new "%s 在夜色中逃走了。"
    old "%s %s and tried to fight back, but Gizel easily subdued her with a binding spell.\n"
    new """%s %s，试图反抗，但 Gizel 用一个束缚法术轻易制服了她。
"""
    old "She lashed out at %s's sanity, sending her into a fit of terror."
    new "她攻击了 %s 的神志，使她陷入极度恐惧。"
    old "She used her powers to force %s into a humiliating pose."
    new "她运用力量强迫 %s 摆出一个屈辱的姿势。"
    old "%s %s training and rebelled against Gizel.\n"
    new """%s %s 训练并反抗了 Gizel。
"""
    old "Incensed by her insolence, Gizel gave her a vicious whipping."
    new "被她的无礼激怒，Gizel 狠狠抽了她一顿鞭子。"
    old "Annoyed, Gizel lost interest and left her to rot in her pen instead."
    new "Gizel 不胜其烦，失去兴趣，把她丢在围栏里自生自灭。"
    old "%s didn't complain as she went into the %s for her training."
    new "%s 乖乖地走进%s接受训练，没有抱怨。"
    old "%s whined and resisted, but Gizel laughed at her and shoved her into the %s anyway."
    new "%s 又哭又闹又求饶，但 Gizel 只是大笑，还是把她推进了%s。"
    old "%s yelled and cried and pleaded, but Gizel dragged her kicking and screaming into the %s."
    new "%s 大喊大叫又苦苦哀求，但 Gizel 连踢带拽地把她拖进了%s。"
    old " Gizel notices %s reacts strongly in the presence of %ss (%s)."
    new " Gizel 注意到 %s 在 %ss（%s）在场时反应强烈。"
    old "weakness discovered"
    new "发现了弱点"
    old " Gizel knows %s is %s, and uses that against her."
    new " Gizel 知道 %s %s，并利用这一点对付她。"
    old "weak against all farm minions"
    new "对农场所有仆从的弱点"
    old " Gizel knows %s is especially %s, and uses that against her."
    new " Gizel 知道 %s 特别%s，并利用这一点对付她。"
    old "weak against %ss"
    new "对 %ss 的弱点"
    old " %s was especially tense and confused. "
    new " %s 特别紧张和困惑。 "
    old "Gizel has discovered she is ambivalent about %s."
    new "Gizel 发现她对 %s 态度矛盾。"
    old " %s struggled, because she has ambivalent feelings about %s."
    new " %s 挣扎得很厉害，因为她对 %s 怀有矛盾的感情。"
    old " %s was blushing and breathing heavily, her nipples visibly erect. "
    new " %s 满脸通红、呼吸急促，乳头明显挺立。 "
    old "Gizel has discovered she likes %s."
    new "Gizel 发现她喜欢 %s。"
    old " %s is turned on by %s acts, so she enjoyed it despite herself."
    new " %s 会被 %s 行为唤起，所以她情不自禁地享受其中。"
    old " %s was tense and uncooperative, and remained fearful for the whole encounter. "
    new " %s 紧张而不配合，全程都心怀恐惧。 "
    old "Gizel has discovered she dislikes %s."
    new "Gizel 发现她厌恶 %s。"
    old " %s doesn't enjoy %s acts, so she remained tense and unwilling."
    new " %s 不喜欢 %s 行为，所以始终紧张而不情愿。"
    old " During training, Gizel discovered one of %s's fixations (%s)!"
    new " 训练期间，Gizel 发现了 %s 的一个癖好（%s）！"
    old " Training was more effective, because Gizel used %s's obsession with %s against her."
    new " 训练效果更好了，因为 Gizel 利用 %s 对 %s 的痴迷来对付她。"
    old " During training, Gizel discovered something %s really hates (%s)."
    new " 训练期间，Gizel 发现了 %s 真正厌恶的东西（%s）。"
    old " Training was more effective, because Gizel used %s's disgust for %s against her."
    new " 训练效果更好了，因为 Gizel 利用 %s 对 %s 的厌恶来对付她。"
    old "\n{color=[c_lightred]}%s has lost her virginity to %s %s!{/color}"
    new """
{color=[c_lightred]}%s 在 %s %s 被夺走了初夜！{/color}"""
    old "Farm unlocked!"
    new "农场已解锁！"

