# TODO: Translation updated at 2026-06-12 05:58

translate chinese_simplified strings:
    old "Do you want to upgrade "
    new "您想升级吗？"
    old "Do you really want to upgrade the "
    new "你真的想升级吗？"
    old "Do you really want to add a pen to the farm for "
    new "你真的想在农场里增设一个畜栏吗？"

# TODO: Translation updated at 2026-06-12 08:13

translate chinese_simplified strings:
    old "The %s can hold %i minion%s (currently: %i). "
    new " %s 可以容纳 %i 个 minion%s（目前：%i）。"
    old "Click here to upgrade the capacity of this facility for %s gold."
    new "点击这里升级该设施处理 %s 黄金的能力。"
    old "Click here to build this facility for %s gold."
    new "点击此处花费%s金币建造该设施。"
    old "You cannot improve this facility until you get a higher brothel license."
    new "在获得更高级别的妓院许可证之前，您无法改善这家设施。"
    old "You cannot improve this facility further."
    new "该设施已无法进一步改进。"
    old "You cannot add a %s to the %s (wrong minion type)."
    new "你不能在 %s 中添加 %s（错误的 minion 类型）。"
    old "%s, a level %s %s, has joined the farm's %s."
    new "%s，一个级别 %s %s，加入了农场的 %s。"
    old "The %s is currently full."
    new "%s当前已满。"
    old "You must build the %s first."
    new "您必须先构建 %s。"
    old "Do you want to upgrade %s to rank %s for %s gold?"
    new "你想花费 %s 金币将 %s 升级到 %s 级吗？"
    old "You do not have enough money to both upgrade the %s and buy the minion."
    new "你没有足够的钱既升级%s又购买小兵。"
    old "The farm's %s has been extended and %s, a level %s %s, has joined."
    new "农场的 %s 已扩展，并且 %s，一个级别 %s %s，已加入。"
    old "That's impossible. The farm's %s is full and cannot be upgraded at the moment."
    new "无法执行。农场的%s已达到上限，目前无法继续升级。"
    old "Level %i %s"
    new "级别 %i %s"
    old "%s refused to train today, so Gizel had her work around the farm instead "
    new " %s今天拒绝训练，所以吉泽尔让她在农场干活。"
    old "(training mode: {i}%s{/i})"
    new "（训练模式：{i}%s{/i}）"
    old "%s was held at the farm today"
    new "今天在农场举行了 %s 活动。"
    old ".\n"
    new " 。"
    old "WRONG: not in training"
    new "错误：未接受培训"

