#### Akagi - 用标签工具生成的适用于青楼之王0.3版本的BK.ini  #### 

## 这个可选文件包含一个特定女孩的高级配置数据。不需要的变量可以删除。 
## 该文件应该命名为“_BK.ini”，并放在相关的girl文件夹中。 
## 整行注释是用双哈希引入的 (##) 
## 使用散列（#）或分号添加同一行注释 (;) 
## 注释: 克隆选项现在是每个选项的一部分，但是仍然支持带有专用[cloning options]部分的遗留格式。 


[identity] 
 
## 角色姓名 ## 
 
first_name = "Akagi" # 如果没有或为空，名字将被随机化 
last_name = "" # 如果没有或为空，她将没有姓氏 
inverted_name = False #如果为True， 全名将显示姓氏在名字之前，例如： 'Spears Britney'。 

## 女孩包数据 ## 
 
creator = "Asushinfever" 
version = "v1.0" # 版本号显示在女孩包的浏览界面，这可以帮助玩家了解你的女孩包是何时更新的。您可以使用您喜欢的任何版本号命名格式。
description = "" # 描述将显示在女孩包的浏览界面。

## 克隆设置 ## 
## 这些选项定义了原始女孩的“克隆体”在生成时的设置。 
## 在一局游戏中只能有一个原始女孩，以及任意数量的克隆人。 

unique = False ##如果为True， 克隆人不会生成，只有本体的女孩。所有其他克隆选项将不起作用。 
keep_first_name = True #如果为True， 克隆人将与本体保持相同的名字
keep_last_name = True #如果为True， 克隆人将与本体保持相同的姓氏
keep_inverted = True #如果为True， 克隆人将遵循您为本体设置的姓名顺序

[base skills] 
 
## 女孩的属性 ##
## 属性评级由1到5 (1 代表很糟糕, 3 代表平均水平, 5 代表远超常人。 游戏内还会产生一些变化。) 
## 对于想要随机生成的属性，跳过设置或将其设置为0 
## 外貌: 影响按摩技师和性交的表现
身材: 影响脱衣舞娘和肛交的表现
魅力: 影响女服务员和侍奉的表现
优雅: 影响表演艺妓和调教的表现
敏感: 影响侍奉和客人的满意度
性欲: 影响性交和接客人数
体质: 影响肛交和精力上限
服从: 影响调教和服从性 
 
beauty = 5
body = 5
charm = 5
refinement = 4
libido = 5
obedience = 2
constitution = 3
sensitivity = 3

## 克隆设置 ##
keep_skills = True # 如果为True, 克隆人将与本体共用一套属性设置



[base positive traits] 
 
## 一个女孩在游戏中只能有2个正面特质。金色特质也视为正面特质。 
## Trait names must be between quotes (), spelled exactly as they are in-game. See BKtraits.rpy for the full list of trait names. 
 
## 女孩将永远具有这些特质（最多nb个特质）。谨慎使用，这会让随机生成的女孩失去神秘感。 
always = [] 
 
## 女孩更容易拥有这些特质。
often = [] 
 
## 女孩更难拥有这些特质。 
rarely = [] 
 
## 女孩无法拥有这些特质。 
never = [ "Loose",  "Rowdy",  "Thief",  "Meek", ] 
 
 
[base negative traits] 
 
## 女孩将永远具有这些特质（最多nb个特质）。谨慎使用，这会让随机生成的女孩失去神秘感。 
always = [] 
 
## 女孩更容易拥有这些特质。 
often = [] 
 
## 女孩更难拥有这些特质。 
rarely = [] 
 
## 女孩无法拥有这些特质。 
never = [ "Square",  "Scruffy",  "Awkward",  "Plain",  "Jaded",  "Homely",  "Rude",  "Oafish",  "Frail",  "Timid",  "Vulnerable", ] 
 
## 克隆设置 ##
keep_traits = False #如果为True，克隆人将与本体共用特质设置


[base personality] 
 
## 个性设置 ##
## 游戏中有24种个性类型: pervert, rebel, cold, nerd, masochist, masochist2, meek, sweet, superficial, bimbo, holy, helper, creep, repressed, schemer, prude, princess, pet, easy, class president, tsundere, loyal, yandere, stubborn
## 一个女孩只能有一种个性。浏览BKinit_variables.rpy中的'gpersonalities'获取详细的个性介绍。

always = [] # 我们不建议设置这一项，这会让随机生成的女孩失去神秘感。 
often = [ "Yandere",  "Bimbo", ]
rarely = []
never = [ "Stubborn",  "Schemer",  "Helper",  "Holy",  "Meek",  "Tsundere", ]

## 克隆设置 ##
keep_personality = True #如果为True，克隆人将与本体共用个性设置


[custom personality] 
 
## Custom Personality Settings ##
## You may include a custom personality for your girl. This will override the 'Base personality' settings.
## This requires the inclusion of an .rpy file in your girl pack with her dialogue lines 

custom_personality = False # set to True to use a custom personality. This will override the 'Base personality' settings.
personality_name = "" # give a name to the personality (warning: using an existing personality name will override that personality)
description = "" # this text will display in the magic notebook when a girl's personality is known
attributes = ("","") # list a pair of attributes the personality will always have (warning: having more than 2 will cause bugs).
dialogue_personality_weight = 3 # # how much weight personality-based lines will be given compared to attribute-based and generic dialogue
dialogue_attribute_weight = 1 # # how much weight attribute-based lines will be given compared to personality-based and generic dialogue
generic_dialogue = True # Disabled, but included here for future-proofing. Bool, decides if this personality allows for generic dialogue or not. Custom dialogue should be provided for all relevant situations if set to False.
personality_dialogue_only = None # A list of topics (with quotes, between [] brackets) for which only personality-based dialogue is allowed (e.g. ["slave first visit", "slave train beg"]). All topics can be found in BKdialogue.rpy

custom_dialogue_label = "" # For more complex custom dialogue, a label can be specified. It will receive the 'girl' object and the dialogue 'topic' as arguments.


[tastes] 

## Tastes are used in chatting dialogue, and for flavor only. You may include answers that are not in vanilla choices.
## Leave the line out or set it to 'None' (without quotes) to randomize.

favorite_color = None 
favorite_food = None 
favorite_drink = None 

disliked_color = None 
disliked_food = None 
disliked_drink = None 

hobbies = None # Hobbies must be a list of two items (with quotes, between [] brackets)

## 克隆设置 ##
keep_tastes = False #如果为True， clones will keep the same tastes and hobbies


[sexual preferences] 
 
## Sex Acts ##
## You can choose positive or negative acts which will be generated more often for this girl. Possible choices are: "naked", "service", "sex", "anal", "fetish", "bisexual" and "group".

favorite_acts = []
disliked_acts = []

## You can choose positive or negative fixations which will be generated more often for this girl. Fixations names are found in 'fix_dict' in the 'BKinit_variables.rpy' file
always_fixations = [] # Always positive. Use with care: it makes girl generation very predictable. 
never_fixations = [] # Never positive.

favorite_fixations = [] # More chance of generating as positive fixation, less as negative.
disliked_fixations = [] # More chance of generating as negative fixation, less as positive.
always_negative_fixations = [] # Always negative. Use with care: it makes girl generation very predictable.
never_negative_fixations = [] # Never negative.

## Prior Sexual Experience ##
sexual_experience = "random" # How much sexual experience she has prior to meeting the player. You can choose between the following: "very experienced", "experienced",  "average", "inexperienced", "very inexperienced", "random". If left out or empty, a random level of experience will be chosen.

## Farm weakness ##
farm_weakness = "monster" # choose between the following values: "stallion", "beast", "monster", "machine", "random"

## Cloning Options ##
keep_sex = False #如果为True， clones will keep the same sexual preferences and experience


[background story] 

## Girl Generation ##
generate_as = "all" # 可以被设置为"all"或局限于"free", "slave", 和"story"。随机遭遇事件女孩不会自动刷新，只有在特定事件中才会出现。
generate_in = "all"  # 可以设置为"all"或一个游戏内的地区、地点的名字。（包括地区的“the”前缀）。那里将作为自由女孩生成的地点。对奴隶市场没有影响。
move_after_meeting = True # Used with the generate_in option (default=True). If True, free girls will move from their starting location normally each week after they have their first interaction with the player. If False, they remain in place. 

## 家乡 ##
## 您可以设置一个自定义的家乡（如果您这样做，请确保包含下面的家乡描述），或者只是 "随机生成"
## 家乡的描述是由女孩亲口诉说的

origin = "random"
origin_description = None

## 背景故事 ##
## 随机的背景故事: 在引号之间写上故事的名字, 例如 BKinit_variables.rpy (e.g. "故事模板1", "故事模板2"...)

always_slave_story = []
often_slave_story = []
rarely_slave_story = []
never_slave_story = []## Custom Story ##
## If provided, this label will be called instead of a random back-story. It must take 'girl' as an argument. Replaces the random slave story above.
## See the 'slave_story' labels in BKinteractions.rpy for examples of how it might work (feel free to set up the events very differently)

story_label = None # provide the custom label name (between quotes)

## Custom City Event ##
## If provided, this label will be called instead of normal city interactions. It must take 'girl' as an argument.
## The regular dialog options can be called from within this custom label by using 'call free_girl_talk(girl)'

city_label = None # provide the custom label name (between quotes)

## Custom Night Event ##
## If provided, this label will be called every night. It must take the 'girl' argument. This could be useful to increment some values, run some tests or reset interactions.
## It is recommended that such labels run silent and add a StoryEvent if necessary.

night_label = None # provide the custom label name (between quotes)

## Custom Interaction ##
## This adds a custom button to the regular slave interact menu. Leave it out or set value to None or empty brackets if you are not using it.

interact_prompt = None # Example usage: ("Visit her room", "my_interaction_label", 1) The first string refers to the caption of the button. The second is the label which will be called upon clicking the button. The integer is the AP cost (for UI display only, it isn't deducted from MC actions outside of your label code for flexibility). It must take 'girl' as an argument.

## Custom Initialization Function ##
## If provided, this function will be called when a girl with this template is created, after randomization.
## Write the function in an init block in _events.rpy or another custom .rpy file.
## It must take 'girl' as an argument. It must not interrupt game flow (python only, no ren'py calls or jumps).

init_function = None # provide a custom function name that is called after girl creation (between quotes)

## 克隆设置 ##
keep_generate_as = False # If False, clones will be generated both as slave and free girls regardless of the original setting. True will keep the 'generate_in' setting as well
keep_background = False #如果为True， 克隆人将拥有相同的家乡和背景故事。
