#!/usr/bin/env python3
"""
Extract translatable strings from .rpy files.
Generates Ren'Py translation files in game/tl/<language>/
"""
import re
import os
import sys
import glob
import hashlib
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent


def extract_strings(filepath):
    """Extract _() and __() strings from a file."""
    strings = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return strings
    
    # Match _("...") or __('...')
    for m in re.finditer(r'[_][_]?\(([\'"])(.*?)\1\)', content):
        quote = m.group(1)
        text = m.group(2)
        strings.append(text)
    
    return strings


def generate_strings_rpy(strings, language, output_path):
    """Generate a Ren'Py strings.rpy file."""
    unique_strings = sorted(set(strings))
    
    lines = [
        f"# Translation file for {language}",
        f"# Auto-generated by extract_translations.py",
        "",
        "translate {} strings:".format(language if language else "english"),
        "",
    ]
    
    for s in unique_strings:
        # Escape quotes
        escaped = s.replace('"', '\\"').replace('{', '{{').replace('}', '}}')
        lines.append(f'    old "{escaped}"')
        lines.append(f'    new ""')
        lines.append("")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated: {output_path} ({len(unique_strings)} strings)")


def main():
    all_strings = []
    
    for filepath in glob.glob(str(ROOT / 'game/**/*.rpy'), recursive=True):
        strings = extract_strings(filepath)
        if strings:
            all_strings.extend(strings)
    
    print(f"Total extracted strings: {len(all_strings)}")
    print(f"Unique strings: {len(set(all_strings))}")
    
    # Generate for each language
    languages = ['english', 'chinese', 'chinese_simplified']
    for lang in languages:
        output_dir = str(ROOT / f'game/tl/{lang}')
        os.makedirs(output_dir, exist_ok=True)
        output_path = f'{output_dir}/strings.rpy'
        generate_strings_rpy(all_strings, lang if lang != 'english' else None, output_path)


if __name__ == '__main__':
    main()
