#!/usr/bin/env python3
"""
Import translations from json_i18n_missing_<language>.xlsx
(generated by tools/audit_json_i18n.py) into strings.rpy.

This is a thin wrapper around import_translated_remaining_v3.py's string
import logic, reading from the JSON i18n audit workbook.
"""
from pathlib import Path
import sys

# Reuse the parsing/formatting/replacement logic from the main importer
from import_translated_remaining_v3 import (
    import_sheet,
    TL_DIR,
)

try:
    import openpyxl
except ImportError:
    print("openpyxl not installed. Install with: pip install openpyxl")
    sys.exit(1)


NEW_PROJECT = Path(r"C:\Users\akxls\Documents\Code\BK\Brothel_King-pc")


def main():
    language = sys.argv[1] if len(sys.argv) > 1 else "chinese_simplified"
    excel_file = NEW_PROJECT / f"json_i18n_missing_{language}.xlsx"

    if not excel_file.exists():
        print(f"Excel file not found: {excel_file}")
        print("Run tools/audit_json_i18n.py first.")
        return

    print(f"Loading {excel_file}...")
    wb = openpyxl.load_workbook(excel_file)

    if "strings" not in wb.sheetnames:
        print("No 'strings' sheet found in workbook.")
        return

    print("\nImporting JSON i18n strings...")
    applied, skipped = import_sheet(wb["strings"], "strings")
    print(f"  Applied: {applied}, Skipped: {skipped}")


if __name__ == "__main__":
    main()
