################################################################################
##  Origins Mod — Translation Manifest
##  EN: Static string manifest for the data-driven origins.json content.
##      The translation extractor only sees LITERAL __() calls, so every
##      name/description in data/origins.json is listed here to enter the
##      translate pipeline. Keep in sync when editing the JSON (or rerun
##      tools/gen_origins_manifest.py).
##  ZH: 数据驱动内容（origins.json）的静态字符串清单。翻译提取器只能
##      识别字面量 __() 调用，因此 JSON 中的每条名称/描述都在此列出以
##      进入翻译管线。编辑 JSON 时请同步维护本文件（或重跑
##      tools/gen_origins_manifest.py）。
################################################################################

init python:
    __("Fallen Noble")
    __("Once a respected aristocrat, now disgraced and broke. Your name still opens doors, even as your purse runs empty.")
    __("Aristocrat")
    __("A duelist-courtier who wins with charm and name. Strong charisma, balanced body.")
    __("Silver Tongue")
    __("Charisma +1.")
    __("Noble Bearing")
    __("Reputation gains +25%.")
    __("The Defender")
    __("May protect a girl when a fight breaks out.")
    __("Sign of Influence")
    __("Love and fear gains +10% brothel-wide.")
    __("Inspiring Presence")
    __("All girls' charm +5.")
    __("Champion's Duel")
    __("Fight challenges +6 (dice).")
    __("Legacy of the House")
    __("Reputation gains +50%.")
    __("Street Thug")
    __("Raised in the slums of Zan. Ruthless and resourceful — people mind their manners around you, even if they don't trust you.")
    __("Enforcer")
    __("A slum brawler who rules the back alleys. Strong body, iron discipline.")
    __("Street Brawler")
    __("Strength +1.")
    __("Menacing Glare")
    __("Fear gains +15% brothel-wide.")
    __("Iron Discipline")
    __("Obedience targets -10 for training and jobs brothel-wide.")
    __("Thick Skin")
    __("Spirit +1.")
    __("Bloodhound")
    __("Kingpin")
    __("Underworld Connections")
    __("Kidnap success +20%. Starting evil reputation +10.")
    __("Merchant Family")
    __("Born into a trading house. You know how to haggle, spot a good deal, and make gold talk.")
    __("Magnate")
    __("A guild magnate who turns every coin twice. Sharp charisma, deep pockets.")
    __("The Haggler")
    __("Buy prices -2%, sell prices +2% (scales with charisma).")
    __("Sharp Deal")
    __("Shop prices -15%.")
    __("Rogue")
    __("Golden Touch")
    __("Sell prices +3% (scales with charisma).")
    __("Fame")
    __("Trade Empire")
    __("Shop prices -15%. Starting gold +500.")
    __("Wandering Mage")
    __("A self-taught spellcaster seeking fortune. Girls are drawn to your mysterious aura.")
    __("Sorcerer")
    __("A wandering caster weaving auras over the brothel. Deep spirit, fragile body.")
    __("Inquisitive")
    __("Minor Aura: Purity")
    __("All girls' beauty +5.")
    __("Minor Aura: Mystery")
    __("Minor Aura: Provocation")
    __("All girls' body +5.")
    __("Meditation")
    __("Minor Aura: Sophistication")
    __("All girls' refinement +5.")
    __("Arcane Focus")
    __("Spell learning +30%.")
    __("Archmage")
    __("Arcane Charm")
    __("Pirate Captain")
    __("A feared sea reaver who lost her ship to mutiny. Zan is where you rebuild your legend — by any means necessary.")
    __("Reaver")
    __("A mutinied sea wolf taking what they want. Hard body, quick hands, no mercy.")
    __("Boarding Party")
    __("Kidnap success +20%.")
    __("Plunder")
    __("Sea Legs")
    __("Dread Captain")
    __("Raiding Party")
    __("Sell prices +5% (plunder sells well). Starting gold +200.")
