# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "%s will {b}Rest{/b} in her cell."
    new "%s 将在她的围栏里{b}休息{/b}。"
    old "%s will improve her {b}%s{/b} from doing chores."
    new "%s 将通过做家务提升她的{b}%s{/b}。"
    old "%s will receive {b}automatic training{/b}"
    new "%s 将接受{b}自动训练{/b}"
    old "%s will receive {b}%s training{/b}"
    new "%s 将接受{b}%s 训练{/b}"
    old ".\nI will assign her an {b}automatic facility{/b}, if there is room."
    new """。
如有空位，我会为她指派一个{b}自动设施{/b}。"""
    old "There might not be enough free minions to take care of her in all your facilities."
    new "可能没有足够的空闲仆从在所有设施里照顾她。"
    old " at the {b}%s{/b}."
    new " 位于{b}%s{/b}。"
    old "There may not be enough valid minions for group training. I may assign her to a different facility if other minions are available."
    new "可能没有足够的可用仆从进行群体训练。如果有其他仆从可用，我可能会把她分配到别的设施。"
    old "There are not enough valid minions in the %s, I may have to rotate this girl in and out of the facility."
    new "%s 中没有足够的可用仆从，我可能需要让这名女孩轮流进出该设施。"
    old "\n{b}Warning{/b}: "
    new """
{b}警告{/b}： """
    old "Gizel will train her in %s acts using minions."
    new "Gizel 将用仆从训练她的 %s 行为。"
    old "\nRequires 2 or 3 free minions at the same facility."
    new """
需要在同一设施中有 2 或 3 个空闲仆从。"""
    old "\nThere are no available minions in this facility."
    new """
该设施中没有可用的仆从。"""
    old "Ah, [MC.name]! Came to check on my pets?"
    new "啊，[MC.name]！来看我的宠物吗？"
    old "My minions are bored... When are you going to send them some new playmates?"
    new "我的仆从们无聊了……你什么时候送些新玩伴来？"
    old "\n\n%i street whores are currently housed in the barn."
    new """

%i 名街头妓女目前关在牲口棚里。"""
    old "[MC.name], come! There is something you must see."
    new "[MC.name]，快来！有件事你必须看看。"
    old "New cards are available! Click here to access the {b}Power Deck{/b}."
    new "新卡牌可用了！点击此处进入{b}力量卡组{/b}。"
    old "Click here to access the {b}Power Deck{/b}."
    new "点击此处进入{b}力量卡组{/b}。"
    old "The farm can host one girl per pen."
    new "农场每个围栏可安置一名女孩。"
    old "\nClick here to add a new pen for %s gold."
    new """
点击此处花 %s 金币新建一个围栏。"""
    old "You cannot build any more pens."
    new "你不能再建更多围栏了。"
    old "Upgrade your brothel to be able to add more pens."
    new "升级你的青楼以容纳更多围栏。"
    old "\n(Currently available pens: %s)"
    new """
（当前可用围栏：%s）"""
    old "%s, Lv. %s"
    new "%s，Lv. %s"
    old "minions"
    new "仆从"
    old "random minions"
    new "随机仆从"
    old "random minion"
    new "随机仆从"
    old "%s will %s in front of all customers.\n"
    new """%s 将在所有顾客面前%s。
"""
    old "do a {b}nude show next to a %s{/b}"
    new "在 %s 旁边做一场{b}裸体表演{/b}"
    old "practice her {b}service skills with a %s{/b}"
    new "用 %s {b}练习她的服务技巧{/b}"
    old "have {b}sex with a %s{/b}"
    new "与 %s {b}做爱{/b}"
    old "have {b}anal sex with a %s{/b}"
    new "与 %s {b}进行肛交{/b}"
    old "do a {b}fetish show with a %s{/b}"
    new "与 %s 做一场{b}恋物表演{/b}"
    old "fuck {b}another girl with a %s{/b}"
    new "用 %s {b}操另一个女孩{/b}"
    old "fuck a {b}group of %s{/b}"
    new "用 %s {b}操一群人{/b}"
    old "\n%s "
    new """
%s """
    old " this: She won't suffer negative consequences, but won't learn as much from the experience."
    new " 这样做：她不会受到负面后果，但从这次经历中学到的东西也较少。"
    old " this: She will suffer from fear and mood penalties, but will learn from the experience."
    new " 这样做：她会受到恐惧和心情惩罚，但会从这次经历中学习。"
    old " this: She will suffer from large fear and mood penalties, and her sanity may fray.\nIt's a gamble: this may cause a large swing in her preference for this act, good or bad."
    new """ 这样做：她会受到大量恐惧和心情惩罚，理智也可能崩溃。
这是一场赌博：这可能导致她对该行为的偏好大幅波动，变好或变坏。"""
    old "%s is hurt and cannot participate."
    new "%s 受伤了，无法参加。"

