# TODO: Translation updated at 2026-09-11 06:39

translate chinese_simplified strings:
    old "Build furniture to unlock various upgrades for the brothel."
    new "建造家具，为你的青楼解锁各种升级。"
    old "Your brothel's current reputation is {b}%s{/b}."
    new "你的青楼当前声望为 {b}%s{/b}。"
    old "Your brothel's current threat level is %s."
    new "你的青楼当前威胁等级为 %s。"
    old "Your brothel's current dirt level is {b}%s{/b}."
    new "你的青楼当前肮脏度为 {b}%s{/b}。"
    old "Your brothel's current threat level is %s. Brothel threat is affected by brothel security and your Strength skill."
    new "你的青楼当前威胁等级为 %s。青楼威胁受青楼安保水平以及你的力量技能影响。"
    old "Buy cleaning material and have Sill and the servants scrub your brothel clean (full clean-up cost: %s gold)."
    new "购买清洁用品，让希露和仆人们把你的青楼彻底打扫干净（全面清洁费用：%s 金币）。"
    old "Add a new bedroom to your brothel for {b}%s gold{/b}. This brothel can only have a maximum of {b}%s bedrooms{/b}."
    new "花费 {b}%s 金币{/b}，为你的青楼添一间新卧室。这座青楼最多只能拥有 {b}%s 间卧室{/b}。"
    old "You cannot add any more bedrooms until you move to another brothel."
    new "在搬到另一座青楼之前，你无法再增加卧室。"
    old "You have reached the maximum number of bedrooms."
    new "你已达到卧室数量上限。"
    old "%s is currently assigned to the master bedroom."
    new "%s 目前被分配到主卧。"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old " and {b}%s{/b} gold for the girls in the farm"
    new " 以及给农场女孩们的 {b}%s{/b} 金币"
    old "No other trainer available"
    new "没有其他训练师可用"
    old "Trainers help your girls learning new skills. Discover new trainers by meeting the people of Zan!"
    new "训练师帮助你的女孩学习新技能。去认识瓒城的居民，发现新的训练师吧！"
    old "{i}Recruit a trainer to help your girls.{/i}"
    new "{i}招募一名训练师来帮助你的女孩。{/i}"
    old "Lv. %i{size=-8}/%i"
    new "Lv. %i{size=-8}/%i"
    old "%s day(s) to complete."
    new "还需 %s 天完成。"
    old "When possible, customers will be matched with girls of the same rank."
    new "在可能的情况下，顾客会与同等级别的女孩配对。"
    old "When possible, customers will be matched with girls that allow their preferred job or sex act."
    new "在可能的情况下，顾客会与允许其偏好工作或性行为的女孩配对。"
    old "Click here to activate or deactivate %s.\n%s ({b}%s{/b})"
    new """点击此处激活或停用 %s。
%s（{b}%s{/b}）"""
    old "active"
    new "active"
    old "inactive"
    new "inactive"
    old "%s to customer attraction"
    new "%s 对顾客吸引力"
    old "%s to customer budget"
    new "%s 对顾客预算"

