# TODO: Translation updated at 2026-09-11 06:39

translate chinese_simplified strings:
    old "{b}%s{/b} is training (%s)."
    new "{b}%s{/b} 正在训练（%s）。"
    old "{b}%s{/b} is being held (%s)."
    new "{b}%s{/b} 正被关押（%s）。"
    old "Click to allow %s"
    new "点击以允许 %s"
    old "Click to block %s"
    new "点击以屏蔽 %s"
    old "Send %s back to the brothel."
    new "将 %s 送回青楼。"

# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "tomorrow"
    new "明天"
    old "tonight"
    new "今晚"
    old "Current badge: {b}%s{/b}.\nClick to change the custom badge for this girl."
    new """当前徽章：{b}%s{/b}。
点击更改该女孩的自定义徽章。"""
    old "Hurt"
    new "受伤"
    old "Tired"
    new "疲倦"
    old "No {u}j{/u}ob"
    new "无{u}工{/u}作"
    old "Half-Shift"
    new "半个班次"
    old "Full shift"
    new "整个班次"
    old "{i}Current schedule: %s{/i}.\nClick to open %s's schedule."
    new """{i}当前日程：%s{/i}。
点击打开 %s 的日程。"""
    old "You cannot interact with %s as she is away."
    new "你无法与 %s 互动，因为她不在。"
    old "Release this free girl from your custody. ({i}shortcut: {u}Backspace{/u}{/i})"
    new "释放这名自由女孩，让她离开你的看管。（{i}快捷键：{u}Backspace{/u}{/i}）"
    old "Acquaintance"
    new "熟人"
    old "Friend"
    new "朋友"
    old "Love interest"
    new "心仪对象"
    old "Girlfriend"
    new "女友"
    old "Lover"
    new "爱人"
    old "Release this girl from your custody. ({i}shortcut: {u}Backspace{/u}{/i})"
    new "释放这名女孩，让她离开你的看管。（{i}快捷键：{u}Backspace{/u}{/i}）"
    old " {size=12} (max){/size}"
    new " {size=12}（上限）{/size}"

