# TODO: Translation updated at 2026-09-25 05:26

translate chinese_simplified strings:
    old "Mod 管理"
    new "Mod 管理"
    old "没有安装任何 v2 Mod。"
    new "没有安装任何 v2 Mod。"
    old "v%s · %s"
    new "v%s · %s"
    old "未知"
    new "未知"
    old "缺少前置: %s"
    new "缺少前置: %s"
    old "常驻"
    new "常驻"
    old "未激活"
    new "未激活"
    old "已启用"
    new "已启用"
    old "已禁用"
    new "已禁用"
    old "禁用"
    new "禁用"
    old "启用"
    new "启用"
    old "更改将在重启游戏后完全生效。"
    new "更改将在重启游戏后完全生效。"
    old "返回"
    new "返回"

